-- LookupMaster
INSERT INTO LookupMaster(Name,DisplayName,DeleteFlag) VALUES('EncounterType','EncounterType',0);

-- LookupItem
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('Registration-encounter','Registration',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('Triage-encounter','Triage',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('ccc-encounter','CCC',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('pmtct-encounter','PMTCT',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('tb-encounter','TB',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('Lab-encounter','Lab',0);
INSERT INTO LookupItem(Name,DisplayName,DeleteFlag) VALUES('Pharmacy-encounter','Pharmacy',0);

-- LookupMasterItem
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='registration-encounter'),'registration-encounter',1);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='triage-encounter'),'triage-encounter',2);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='ccc-encounter'),'ccc-encounter',3);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='pmtct-encounter'),'pmtct-encounter',4);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='tb-encounter'),'tb-encounter',5);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='lab-encounter'),'lab-encounter',6);
INSERT INTO LookupMasterItem(LookupMasterId,LookupItemId,DisplayName,OrdRank) VALUES((SELECT top 1 id FROM LookupMaster l WHERE l.Name='EncounterType'),(SELECT TOP 1 Id FROM LookupItem i WHERE i.Name='Pharmacy-encounter'),'Pharmacy-encounter',7);

---duplicate PMTCT Regimens
update LookupMasterItem set LookupItemId=(select id from lookupitem where name = 'PMTCTRegimens') 
where LookupItemId=(select id from lookupitem where name = 'PMTCT Regimens')

------------------Add MFL Facilities------------------------------------
insert into [FacilityList] values(10056,'Bennedict XVI Dispensary')
insert into [FacilityList] values(10189,'GK Prison Dispensary')
insert into [FacilityList] values(10194,'Gachege Dispensary')
insert into [FacilityList] values(10195,'Gachika Dispensary')
insert into [FacilityList] values(10199,'Gaichanjiru Hospital')
insert into [FacilityList] values(10202,'Gakoe Health Centre')
insert into [FacilityList] values(10203,'Gakurwe Dispensary')
insert into [FacilityList] values(10222,'Gatitu Dispensary')
insert into [FacilityList] values(10245,'Geta Forest Dispensary')
insert into [FacilityList] values(10265,'Githirioni Dispensary')
insert into [FacilityList] values(10360,'Itiati Dispensary')
insert into [FacilityList] values(10390,'Kabiruini Health Clinic')
insert into [FacilityList] values(10413,'Kagwe Dispensary')
insert into [FacilityList] values(10435,'Kaiyaba Dispensary')
insert into [FacilityList] values(10440,'Kamae Forest Dispensary')
insert into [FacilityList] values(10459,'Kandara Sub County Hospital')
insert into [FacilityList] values(10476,'Karaba Health Centre (Nyeri South)')
insert into [FacilityList] values(10518,'Immaculate Heart Hospital Kereita')
insert into [FacilityList] values(10602,'Kijabe (AIC) Hospital')
insert into [FacilityList] values(10610,'Kimende Orthodox Mission Health Centre')
insert into [FacilityList] values(10693,'Kijabe (AIC) Hospital Marira Medical Clinic')
insert into [FacilityList] values(10774,'Munyu Health Centre')
insert into [FacilityList] values(10823,'Narumoru Disabled Childrens Home')
insert into [FacilityList] values(10857,'Ngararia Dispensary')
insert into [FacilityList] values(10875,'Nguthuru Dispensary')
insert into [FacilityList] values(10891,'Nyahururu Private Hospital')
insert into [FacilityList] values(10987,'Sabasaba Health Centre')
insert into [FacilityList] values(11069,'St Teresa Catholic Dispensary')
insert into [FacilityList] values(11127,'Turuturu Dispensary')
insert into [FacilityList] values(11237,'Bamba Sub District Hospital')
insert into [FacilityList] values(11238,'Bamba Medical Clinic')
insert into [FacilityList] values(11242,'Bangali Dispensary')
insert into [FacilityList] values(11263,'Bura Health Centre (Taita Taveta)')
insert into [FacilityList] values(11264,'Bura  Sub county Hospital')
insert into [FacilityList] values(11281,'Charidende Dispensary (CDF)')
insert into [FacilityList] values(11284,'Chewele Dispensary')
insert into [FacilityList] values(11305,'Dida Dispensary')
insert into [FacilityList] values(11308,'Divine Mercy Dispensary')
insert into [FacilityList] values(11320,'Dr Kasamjee Medical Clinic')
insert into [FacilityList] values(11344,'Dr Mustafa Kamani Clinic')
insert into [FacilityList] values(11359,'Dzikunze Dispensary')
insert into [FacilityList] values(11383,'Ganze Health Centre')
insert into [FacilityList] values(11430,'Jaribuni Dispensary')
insert into [FacilityList] values(11453,'Kakuyuni Dispensary (Malindi)')
insert into [FacilityList] values(11475,'Kilifi Plantation Dispensary')
insert into [FacilityList] values(11480,'Kinango District Hospital')
insert into [FacilityList] values(11495,'Kizibe Dispensary')
insert into [FacilityList] values(11532,'Madamani Dispensary')
insert into [FacilityList] values(11533,'Madogo Health Centre')
insert into [FacilityList] values(11549,'Maktau Health Centre')
insert into [FacilityList] values(11553,'Malanga (AIC) Dispensary')
insert into [FacilityList] values(11567,'Marie Stopes Kenya Clinic (Malindi)')
insert into [FacilityList] values(11574,'Marynoll Dispensary')
insert into [FacilityList] values(11588,'Mbalambala Dispensary')
insert into [FacilityList] values(11609,'Midoina Dispensary')
insert into [FacilityList] values(11618,'Mirihini Dispensary')
insert into [FacilityList] values(11635,'Mlanjo Dispensary')
insert into [FacilityList] values(11653,'Muryachakwe Dispensary')
insert into [FacilityList] values(11663,'Mtaani Clinic')
insert into [FacilityList] values(11699,'Nanighi Dispensary (Tana River)')
insert into [FacilityList] values(11730,'Palakumi Dispensary')
insert into [FacilityList] values(11802,'Sokoke Dispensary')
insert into [FacilityList] values(11804,'Sombo Dispensary')
insert into [FacilityList] values(11829,'Star Hospital')
insert into [FacilityList] values(11845,'Chamalo Medical Clinic')
insert into [FacilityList] values(11859,'Tsangatsini Dispensary')
insert into [FacilityList] values(11883,'Vitengeni Health Centre')
insert into [FacilityList] values(11917,'78 Tank Battalion Dispensary')
insert into [FacilityList] values(11932,'Approved School Dispensary (Machakos)')
insert into [FacilityList] values(11987,'Don Bosco Clinic')
insert into [FacilityList] values(12009,'Endei Dispensary')
insert into [FacilityList] values(12012,'Eremet Dispensary')
insert into [FacilityList] values(12074,'Iiani/Kiatineni Dispensary')
insert into [FacilityList] values(12082,'Ikuyuni Dispensary')
insert into [FacilityList] values(12164,'Kamumu Dispensary')
insert into [FacilityList] values(12169,'Kamuwongo Dispensary')
insert into [FacilityList] values(12185,'Kanyuambora Dispensary')
insert into [FacilityList] values(12206,'Kaseve Medical Clinic')
insert into [FacilityList] values(12226,'Kathanje Dispensary')
insert into [FacilityList] values(12247,'Katumani Dispensary')
insert into [FacilityList] values(12253,'Kaumu Health Centre')
insert into [FacilityList] values(12271,'Kiambere Dam Dispensary')
insert into [FacilityList] values(12279,'Kianjokoma Sub-District Hospital')
insert into [FacilityList] values(12289,'Kibunga Sub-District Hospital')
insert into [FacilityList] values(12293,'Kiengu PCEA Dispensary')
insert into [FacilityList] values(12313,'Kilome Nursing Home')
insert into [FacilityList] values(12333,'Kirie Dispensary')
insert into [FacilityList] values(12334,'Kirie Mission Clinic')
insert into [FacilityList] values(12379,'Kivuuni Dispensary')
insert into [FacilityList] values(12381,'Kola Health Centre')
insert into [FacilityList] values(12425,'Lasida Clinic')
insert into [FacilityList] values(12459,'Malalani Health Centre')
insert into [FacilityList] values(12460,'Maliku Health Centre')
insert into [FacilityList] values(12590,'Muthanthara Dispensary')
insert into [FacilityList] values(12628,'Mwitika Health Centre')
insert into [FacilityList] values(12733,'Siakago Clinic')
insert into [FacilityList] values(12793,'Thanantu Faith Clinic Dispensary')
insert into [FacilityList] values(12796,'Thinu Health Centre')
insert into [FacilityList] values(12823,'Ungatu Dispensary')
insert into [FacilityList] values(12842,'Wanzoa Dispensary')
insert into [FacilityList] values(12853,'Yatta Health Centre')
insert into [FacilityList] values(12865,'Afwan Medical Centre')
insert into [FacilityList] values(12887,'Brother andre Clinic')
insert into [FacilityList] values(12902,'Compassionate Hospital')
insert into [FacilityList] values(12913,'Dandora I Health Centre')
insert into [FacilityList] values(12973,'Huruma (EDARP)')
insert into [FacilityList] values(12982,'Mary Immaculate Clinic Mukuru')
insert into [FacilityList] values(13028,'Kibera Community Health Centre - Amref')
insert into [FacilityList] values(13037,'Kmtc Dispensary')
insert into [FacilityList] values(13053,'Lunga Lunga Health Centre')
insert into [FacilityList] values(13064,'Mariakani Cottage Hospital Ltd')
insert into [FacilityList] values(13157,'Pumwani Maternity VCT Centre')
insert into [FacilityList] values(13171,'Ruai Health Centre')
insert into [FacilityList] values(13179,'Senye Medical Clinic')
insert into [FacilityList] values(13234,'Tabitha Medical Clinic')
insert into [FacilityList] values(13303,'Basir Dispensary')
insert into [FacilityList] values(13318,'Dagahaley Hospital')
insert into [FacilityList] values(13349,'Gither Dispensary')
insert into [FacilityList] values(13431,'Sangailu Health Centre')
insert into [FacilityList] values(13475,'Amatierio Dispensary')
insert into [FacilityList] values(13535,'Dolphil Nursing & Maternity Home')
insert into [FacilityList] values(13539,'Egetuki Medical Clinic (Gucha)')
insert into [FacilityList] values(13547,'Eronge Health Centre')
insert into [FacilityList] values(13568,'Geteri Dispensary')
insert into [FacilityList] values(13570,'Getongoroma Health Centre')
insert into [FacilityList] values(13574,'Gietai (AIC) Dispensary')
insert into [FacilityList] values(13584,'Godber Dispensary')
insert into [FacilityList] values(13586,'Gods Will Clinic')
insert into [FacilityList] values(13621,'Irondi Dispensary')
insert into [FacilityList] values(13693,'Kimonge Dispensary')
insert into [FacilityList] values(13722,'Kowino Dispensary')
insert into [FacilityList] values(13735,'Ligega Health Centre')
insert into [FacilityList] values(13790,'Matongo Dispensary')
insert into [FacilityList] values(13797,'Mbaga Health Centre')
insert into [FacilityList] values(13799,'Uluthe Dispensary')
insert into [FacilityList] values(13807,'Migosi Sub County Hospital')
insert into [FacilityList] values(13811,'Miriri Dispensary')
insert into [FacilityList] values(13821,'Monianku Health Centre')
insert into [FacilityList] values(13851,'Ngisiru Dispensary')
insert into [FacilityList] values(13924,'Nyangena Sub District Hospital (Manga)')
insert into [FacilityList] values(13932,'Nyankono Dispensary')
insert into [FacilityList] values(13949,'NYS Dispensary (Suba)')
insert into [FacilityList] values(13951,'Obanga Health Centre')
insert into [FacilityList] values(13988,'Ongito Dispensary')
insert into [FacilityList] values(14105,'St Consolata Clinic')
insert into [FacilityList] values(14157,'Ulanda Dispensary')
insert into [FacilityList] values(14214,'Arpollo Dispensary')
insert into [FacilityList] values(14284,'Chagaiya Dispensary')
insert into [FacilityList] values(14288,'Chebaiwa Dispensary')
insert into [FacilityList] values(14294,'Chebiemit District Hospital')
insert into [FacilityList] values(14301,'Chebororwa Health Centre')
insert into [FacilityList] values(14317,'Chembulet Health Centre')
insert into [FacilityList] values(14323,'Chemosot Health Centre')
insert into [FacilityList] values(14335,'Chepkanga Health Centre')
insert into [FacilityList] values(14343,'Chepkoilel Campus Dispensary')
insert into [FacilityList] values(14371,'Cheptil Dispensary')
insert into [FacilityList] values(14415,'Dr Mugo Medical Clinic')
insert into [FacilityList] values(14418,'Dr Ngotho Medical Clinic')
insert into [FacilityList] values(14485,'Ewaso Ngiro Health Centre')
insert into [FacilityList] values(14486,'Ewuaso Kedong Dispensary')
insert into [FacilityList] values(14513,'GOK Farm (Nahrc) Dispensary')
insert into [FacilityList] values(14519,'GK Prisons Dispensary (Eldoret East)')
insert into [FacilityList] values(14535,'Grand Avens Clinic')
insert into [FacilityList] values(14559,'Ikumbi Health Centre')
insert into [FacilityList] values(14570,'Tingwa Dispensary')
insert into [FacilityList] values(14631,'Kabulwo Dispensary')
insert into [FacilityList] values(14633,'Kabutii-Matiret Dispensary')
insert into [FacilityList] values(14635,'Kacheliba Mobile Clinic')
insert into [FacilityList] values(14669,'Kamasai Dispensary')
insert into [FacilityList] values(14678,'Kamurio Dispensary')
insert into [FacilityList] values(14680,'Kamwosor sub-county hospital')
insert into [FacilityList] values(14703,'Kapkagaron Dispensary')
insert into [FacilityList] values(14713,'Kapkeringoon Dispensary')
insert into [FacilityList] values(14721,'Kapkoi Health Centre')
insert into [FacilityList] values(14743,'Kapluk Dispensary')
insert into [FacilityList] values(14745,'Kapngombe Dispensary')
insert into [FacilityList] values(14750,'Kapsait Dispensary')
insert into [FacilityList] values(14752,'Kapsaos Dispensary')
insert into [FacilityList] values(14774,'Kaptalamwa Health Centre')
insert into [FacilityList] values(14775,'Kaptorokwa Dispensary')
insert into [FacilityList] values(14786,'Kaptiony Dispensary (Marakwet)')
insert into [FacilityList] values(14802,'Karati Dispensary')
insert into [FacilityList] values(14804,'Karuna Dispensary')
insert into [FacilityList] values(14850,'Kibigos Dispensary')
insert into [FacilityList] values(14851,'Kibingor Dispensary')
insert into [FacilityList] values(14854,'Kibish Dispensary')
insert into [FacilityList] values(14874,'Kimnai Dispensary')
insert into [FacilityList] values(14879,'Kimoning Dispensary')
insert into [FacilityList] values(14902,'Kiplalmat Dispensary')
insert into [FacilityList] values(14910,'Kipsamoite Dispensary')
insert into [FacilityList] values(14928,'Kiptere Dispensary')
insert into [FacilityList] values(14936,'Kiratina Medical Clinic')
insert into [FacilityList] values(14969,'Koitugum Dispensary')
insert into [FacilityList] values(14976,'Kokwa Dispensary')
insert into [FacilityList] values(14984,'Kondabilet Dispensary')
insert into [FacilityList] values(15011,'Langas RCEA')
insert into [FacilityList] values(15069,'Lolkeringet Dispensary')
insert into [FacilityList] values(15091,'Loruk Dispensary (East Pokot)')
insert into [FacilityList] values(15135,'Marie Stopes Health Centre (Eldoret West)')
insert into [FacilityList] values(15141,'Maron Dispensary')
insert into [FacilityList] values(15145,'Marura Dispensary')
insert into [FacilityList] values(15169,'Meibeki Dispensary')
insert into [FacilityList] values(15171,'Menet Dispensary')
insert into [FacilityList] values(15192,'Mochongoi Health Centre')
insert into [FacilityList] values(15201,'Mogwa Dispensary')
insert into [FacilityList] values(15206,'Moiben Health Centre')
insert into [FacilityList] values(15249,'Mukutani Dispensary (East Pokot)')
insert into [FacilityList] values(15253,'Muramati Dispensary')
insert into [FacilityList] values(15284,'Nakalei Dispensary')
insert into [FacilityList] values(15287,'Nakuru Nursing Home')
insert into [FacilityList] values(15290,'Nakuru West (PCEA) Health Centre')
insert into [FacilityList] values(15291,'Nakururum Dispensary')
insert into [FacilityList] values(15326,'Ndoinet Dispensary')
insert into [FacilityList] values(15330,'Neema Medical Clinic (Nakuru North)')
insert into [FacilityList] values(15399,'Olepolos Dispensary')
insert into [FacilityList] values(15420,'Olokurto Health Centre')
insert into [FacilityList] values(15478,'Railways Dispensary')
insert into [FacilityList] values(15486,'Riongo Dispensary')
insert into [FacilityList] values(15542,'Sekerr Dispensary')
insert into [FacilityList] values(15567,'Sigot Dispensary')
insert into [FacilityList] values(15570,'Silibwet Dispensary (Bomet)')
insert into [FacilityList] values(15577,'Simotwo Dispensary (Eldoret East)')
insert into [FacilityList] values(15581,'Sinai Mount Hospital')
insert into [FacilityList] values(15599,'Siyiapei (AIC) Dispensary')
insert into [FacilityList] values(15604,'Sogon Dispensary')
insert into [FacilityList] values(15610,'Songeto Dispensary')
insert into [FacilityList] values(15648,'St Kevina Dispensary')
insert into [FacilityList] values(15706,'Tangasir Dispensary')
insert into [FacilityList] values(15716,'Tenden Dispensary')
insert into [FacilityList] values(15718,'Tenges Health Centre')
insert into [FacilityList] values(15725,'Timboroa Health Centre')
insert into [FacilityList] values(15731,'Todonyang Dispensary')
insert into [FacilityList] values(15736,'Tororek Dispensary')
insert into [FacilityList] values(15741,'Tugen Estate Dispensary')
insert into [FacilityList] values(15758,'Uasin Gishu District Hospital')
insert into [FacilityList] values(15809,'Boyani Dispensary')
insert into [FacilityList] values(15862,'Coptic Nursing Home')
insert into [FacilityList] values(15876,'Emuhaya Sub County Referral Hospital')
insert into [FacilityList] values(15976,'Lurare Dispensary')
insert into [FacilityList] values(16003,'Matayos Community Clinic')
insert into [FacilityList] values(16022,'Mois Bridge Nursing Home')
insert into [FacilityList] values(16179,'Maryango Medical Clinic')
insert into [FacilityList] values(16215,'Catholic Hospital Laisamis')
insert into [FacilityList] values(16315,'Tolilet Dispensary')
insert into [FacilityList] values(16354,'Kapkei Dispensary')
insert into [FacilityList] values(16361,'Bikeke Health Centre')
insert into [FacilityList] values(16382,'Ngondi Dispensary')
insert into [FacilityList] values(16399,'Mukorombosi Dispensary')
insert into [FacilityList] values(16415,'Kewamoi Dispensary')
insert into [FacilityList] values(16419,'Paula Nursing Home')
insert into [FacilityList] values(16455,'Joint Partner Medical Clinic')
insert into [FacilityList] values(16457,'Kaptisi Dispensary')
insert into [FacilityList] values(16460,'Mutiva Dispensary')
insert into [FacilityList] values(16464,'Ishiara Sub-District Hospital')
insert into [FacilityList] values(16467,'Mbeere District Hospital')
insert into [FacilityList] values(16468,'Riandu Dispensary')
insert into [FacilityList] values(16472,'Kitoi Dispensary')
insert into [FacilityList] values(16487,'Ruanda Dispensary')
insert into [FacilityList] values(16488,'Kubura Dispensary')
insert into [FacilityList] values(16531,'Avenue Health Care')
insert into [FacilityList] values(16652,'Yathui Dispensary')
insert into [FacilityList] values(16689,'Narolong Dispensary (Trans Mara West)')
insert into [FacilityList] values(16690,'Ololchani Dispensary')
insert into [FacilityList] values(16701,'Chepturnguny Dispensary')
insert into [FacilityList] values(16717,'Ikuywa Dispensary')
insert into [FacilityList] values(16719,'Shinyalu Central Clinic')
insert into [FacilityList] values(16722,'Burutu Dspensary')
insert into [FacilityList] values(16723,'Koisagat Dispensary (Kipkelion)')
insert into [FacilityList] values(16731,'Chemsik Dispensary')
insert into [FacilityList] values(16736,'Chepturu Dispensary')
insert into [FacilityList] values(16737,'Kapunyany Dispensary')
insert into [FacilityList] values(16818,'Kangocho Dispensary')
insert into [FacilityList] values(16869,'Mogusii Clinic')
insert into [FacilityList] values(16989,'Kianginda Health Centre')
insert into [FacilityList] values(16996,'Mbitini (ACK) Dispensary')
insert into [FacilityList] values(17012,'Alikune Dispensary')
insert into [FacilityList] values(17025,'Menegai Medical Clinic')
insert into [FacilityList] values(17042,'Mokoyon Dispensary')
insert into [FacilityList] values(17056,'Barsemoi Dispensary')
insert into [FacilityList] values(17057,'Mukarara Dispensary')
insert into [FacilityList] values(17066,'Thumbereria Dispensary')
insert into [FacilityList] values(17072,'Boka')
insert into [FacilityList] values(17073,'Koshok Dispensary')
insert into [FacilityList] values(17076,'Kapkoto Dispensary')
insert into [FacilityList] values(17079,'Meti Dispensary')
insert into [FacilityList] values(17081,'Buwa')
insert into [FacilityList] values(17084,'Nakurtakwei Dispensary')
insert into [FacilityList] values(17103,'Sutyechun Dispensary')
insert into [FacilityList] values(17106,'Kangonde Health Centre')
insert into [FacilityList] values(17114,'Rekeke Model Health Centre')
insert into [FacilityList] values(17126,'Modambogho Dispensary')
insert into [FacilityList] values(17160,'Kishaunet Dispensary')
insert into [FacilityList] values(17163,'Kavatanzou Dispensary')
insert into [FacilityList] values(17178,'Namirama Dispensary')
insert into [FacilityList] values(17219,'Kasphat Dispensary')
insert into [FacilityList] values(17222,'Jabali Dispensary')
insert into [FacilityList] values(17239,'Cheplelabei Dispensary')
insert into [FacilityList] values(17240,'Sinonin Dispensary')
insert into [FacilityList] values(17244,'Ngecha Health Centre')
insert into [FacilityList] values(17248,'Rironi Dispensary')
insert into [FacilityList] values(17262,'Kawiru Dispensary')
insert into [FacilityList] values(17278,'Loikumkum Dispensary')
insert into [FacilityList] values(17300,'Naramam Dispensary')
insert into [FacilityList] values(17322,'Sitoka Dispensary')
insert into [FacilityList] values(17338,'Labasigale Dispensary')
insert into [FacilityList] values(17351,'Eldume Dispensary')
insert into [FacilityList] values(17356,'Katote Dispensary')
insert into [FacilityList] values(17358,'Chesunet Dispensary')
insert into [FacilityList] values(17360,'Barakeiywo Dispensary')
insert into [FacilityList] values(17374,'Shauri Dispensary')
insert into [FacilityList] values(17380,'Kililii Dispensary')
insert into [FacilityList] values(17381,'Kaelo Dispensary')
insert into [FacilityList] values(17383,'Naikuriu Dispensary')
insert into [FacilityList] values(17403,'Tulwet Dispensary')
insert into [FacilityList] values(17469,'Kiteje Dispensary')
insert into [FacilityList] values(17485,'Moi Baracks')
insert into [FacilityList] values(17520,'Got Regea Dispensary')
insert into [FacilityList] values(17528,'Matibabu Nzoia Clinic')
insert into [FacilityList] values(17550,'Yikivumbu Dispensary')
insert into [FacilityList] values(17551,'Matutu Dispensary (Nzaui)')
insert into [FacilityList] values(17593,'Remba Dispensary')
insert into [FacilityList] values(17635,'Kapchepkok Dispensary')
insert into [FacilityList] values(17650,'Johanna Justin-Jinich Community Clinic (Kibera)')
insert into [FacilityList] values(17654,'Mother of Mercy (Machakos)')
insert into [FacilityList] values(17689,'Viragoni Dispensary')
insert into [FacilityList] values(17706,'Taqwa Nursing Home')
insert into [FacilityList] values(17710,'Ringiti Dispensary')
insert into [FacilityList] values(17732,'Royal Clinic')
insert into [FacilityList] values(17758,'Kaptum Keiyo Dispensary')
insert into [FacilityList] values(17772,'Kapkoros Dispensary (Tinderet)')
insert into [FacilityList] values(17779,'Muvuko Dispensary')
insert into [FacilityList] values(17781,'Rongena Dispensary (Narok West)')
insert into [FacilityList] values(17784,'Enkutoto Dispensary')
insert into [FacilityList] values(17787,'Fountain Medical Clinic')
insert into [FacilityList] values(17823,'Mundoro Community')
insert into [FacilityList] values(17873,'Tuiyoluk Dispensary')
insert into [FacilityList] values(17890,'Sabor Forest Dispensary')
insert into [FacilityList] values(17925,'Erreteti Dispensary')
insert into [FacilityList] values(17943,'St Francis Community Hospital (Kasarani)')
insert into [FacilityList] values(17944,'Samoei Medical Clinic')
insert into [FacilityList] values(17966,'The Omari Project')
insert into [FacilityList] values(17985,'Civil Servants Clinic (Nakuru)')
insert into [FacilityList] values(18008,'Mutulani Dispensary')
insert into [FacilityList] values(18010,'Tachasis Dispensary')
insert into [FacilityList] values(18012,'Watanu SDA Dispensary')
insert into [FacilityList] values(18013,'Ruguru Community Health Centre')
insert into [FacilityList] values(18077,'Kiembe Dispensary')
insert into [FacilityList] values(18123,'Wahome Health Clinic')
insert into [FacilityList] values(18171,'Administration Police Senior Staff College Dispens')
insert into [FacilityList] values(18177,'Imani Hospital')
insert into [FacilityList] values(18185,'Kapterit Dispensary')
insert into [FacilityList] values(18186,'Kipkundul Dispensary')
insert into [FacilityList] values(18199,'Nyumbani Village Catholic Dispensary')
insert into [FacilityList] values(18204,'Kokwongoi Dispensary')
insert into [FacilityList] values(18207,'Kapchemuta Dispensary')
insert into [FacilityList] values(18208,'Busieso Dispensary')
insert into [FacilityList] values(18268,'Kogari Dispensary')
insert into [FacilityList] values(18269,'Muchonoke Dispensary')
insert into [FacilityList] values(18297,'Huruma Medical Clinic (Bamba)')
insert into [FacilityList] values(18298,'Mother and Child Clinic Malindi')
insert into [FacilityList] values(18302,'Maweni Community Clinic')
insert into [FacilityList] values(18308,'GK Prison Clinic')
insert into [FacilityList] values(18309,'Mtoroni Dispensary')
insert into [FacilityList] values(18370,'Lomekwi Dispensary')
insert into [FacilityList] values(18377,'Multipurpose Village Health Care Centre')
insert into [FacilityList] values(18380,'Peak Health Medical Centre')
insert into [FacilityList] values(18452,'Karerema Dispensary')
insert into [FacilityList] values(18453,'Gatiruri Dispensary')
insert into [FacilityList] values(18500,'Ngieni Community Dispensary')
insert into [FacilityList] values(18507,'Muselele Dispensary')
insert into [FacilityList] values(18514,'Kathome Health Centre')
insert into [FacilityList] values(18517,'Zennith Community Project')
insert into [FacilityList] values(18583,'Chemworemwo Dispensary')
insert into [FacilityList] values(18591,'Meridian Medical Centre (Capital Centre)')
insert into [FacilityList] values(18605,'Mid-Town Reoproductive Health and Youth Friendly')
insert into [FacilityList] values(18610,'Atela Dispensary')
insert into [FacilityList] values(18668,'Reinha Rosary Medical Clinic (Githunguri)')
insert into [FacilityList] values(18669,'Eldoret Rapha Medical Centre')
insert into [FacilityList] values(18675,'Huhoini Dispensary')
insert into [FacilityList] values(18688,'Menengai Crator Dispensary')
insert into [FacilityList] values(18766,'Sasa Centre')
insert into [FacilityList] values(18774,'Port Florence Clinic')
insert into [FacilityList] values(18784,'Lenana Hills Hospital')
insert into [FacilityList] values(18792,'New Hope Clinic (Nyamira)')
insert into [FacilityList] values(18802,'Kamashia')
insert into [FacilityList] values(18807,'Dr Irimu Medical Clinic')
insert into [FacilityList] values(18848,'Kiangua Dispensary')
insert into [FacilityList] values(18868,'Matabithi Dispensary')
insert into [FacilityList] values(18872,'K K Mwethe Diispensary')
insert into [FacilityList] values(18910,'Burgabo Dispensary')
insert into [FacilityList] values(18912,'Mama Anns Odede Community Health Centre')
insert into [FacilityList] values(18958,'Ndunguni Dispensary')
insert into [FacilityList] values(18970,'Machengene Dispensary')
insert into [FacilityList] values(18976,'Kitengela Medical Services Kajiado')
insert into [FacilityList] values(18983,'Reale Medical Clinic')
insert into [FacilityList] values(19024,'Dungicha Dispensary')
insert into [FacilityList] values(19114,'Hope World Wide')
insert into [FacilityList] values(19119,'St Joseph Medical Clinic Kathiani')
insert into [FacilityList] values(19141,'Thuuru Dispensary')
insert into [FacilityList] values(19146,'Thamare Dispensary')
insert into [FacilityList] values(19233,'Kiima Kiu Dispensary')
insert into [FacilityList] values(19271,'Swop Korogocho')
insert into [FacilityList] values(19412,'Shalom Satelite Clinic')
insert into [FacilityList] values(19415,'Ngumbulu Dispensary')
insert into [FacilityList] values(19646,'Dr Mboloi Clinic')
insert into [FacilityList] values(19726,'Kyaimu Dispensary')
insert into [FacilityList] values(19736,'Kishon Health centre')
insert into [FacilityList] values(19750,'Cheptantan Dispensary')
insert into [FacilityList] values(19865,'Wikoteng Dispensary')
insert into [FacilityList] values(19902,'Nduluni Dispensary')
insert into [FacilityList] values(19903,'Muua Dispensary')
insert into [FacilityList] values(19906,'Queens & Kings Health Centre')
insert into [FacilityList] values(19923,'Ndelekeni Dispensary')
insert into [FacilityList] values(19924,'Mikuyuni Disp')
insert into [FacilityList] values(19925,'Kakuku Dispensary')
insert into [FacilityList] values(19961,'Dr J A Alouch')
insert into [FacilityList] values(19977,'Kavete Dispensary (Makindu)')
insert into [FacilityList] values(19978,'Ndalani Dispensary (Makindu)')
insert into [FacilityList] values(19979,'Dr Mureithi Clinic (Kilimani)')
insert into [FacilityList] values(19981,'Dr Muhindi Clinic (Kilimani)')
insert into [FacilityList] values(19982,'Dr Kingondu Clinic (Kilimani)')
insert into [FacilityList] values(19986,'Masokani Dispensary')
insert into [FacilityList] values(19987,'Mbiini Dispensary')
insert into [FacilityList] values(19988,'Kavuko Dispensary')
insert into [FacilityList] values(19991,'Isumba Dispensary')
insert into [FacilityList] values(19998,'Karatina Model Health Centre')
insert into [FacilityList] values(20013,'Maliera Mission Dispensary')
insert into [FacilityList] values(20036,'Mmangani Dispensary')
insert into [FacilityList] values(20048,'Lomuke Dispensary')
insert into [FacilityList] values(20051,'Oasis Doctors Plaza Medical Centre')
insert into [FacilityList] values(20056,'Nasha Lengot Medical Centre')
insert into [FacilityList] values(20097,'Inuka Nursing Home')
insert into [FacilityList] values(20122,'Dr Ogindos Clinic')
insert into [FacilityList] values(20125,'Katilini Dispensary')
insert into [FacilityList] values(20128,'Kisoi Munyao Memorial Dispensary')
insert into [FacilityList] values(20129,'Nduluku Dispensary')
insert into [FacilityList] values(20139,'St Luke Clinic')
insert into [FacilityList] values(20153,'Kasewe Dispensary')
insert into [FacilityList] values(20256,'Kyumbe Dispensary')
insert into [FacilityList] values(20265,'Afya Medical Clinic (Mbaruk)')
insert into [FacilityList] values(20299,'Kimeswon Health Centre')
insert into [FacilityList] values(20308,'Chamari Dispensary')
insert into [FacilityList] values(20316,'Kokwotendwo Dispensary')
insert into [FacilityList] values(20318,'Orwa dispensary')
insert into [FacilityList] values(20319,'North Shore Medical Centre')
insert into [FacilityList] values(20320,'Africa Muslim Agency Dispensary (Kilifi)')
insert into [FacilityList] values(20321,'Khairat Medical Centre')
insert into [FacilityList] values(20330,'Chepkono Dispensary')
insert into [FacilityList] values(20342,'Malanga Dispensary (Vitengeni)')
insert into [FacilityList] values(20358,'Wargadud Dispensary')
insert into [FacilityList] values(20378,'St.Teresa Hospital Kiambu')
insert into [FacilityList] values(20403,'Jacaranda Maternity  (Kiamumbi )')
insert into [FacilityList] values(20492,'Pemba Dispensary')
insert into [FacilityList] values(20497,'Ciakathukure Dispensary')
insert into [FacilityList] values(20498,'Kiogogo Dispensary')
insert into [FacilityList] values(20499,'Kanyangi Dispensary')
insert into [FacilityList] values(20507,'Ulafu Dispensary')
insert into [FacilityList] values(20509,'Kamweli Dispensary')
insert into [FacilityList] values(20541,'Whiterose Medical Centre')
insert into [FacilityList] values(20548,'Narok Cottage Hospital')
insert into [FacilityList] values(20550,'Dr Walumbe Medical Clinic')
insert into [FacilityList] values(20554,'Dr Mwangi')
insert into [FacilityList] values(20561,'Kamwimbi Dispensary')
insert into [FacilityList] values(20603,'Gurumesa Dispensary')
insert into [FacilityList] values(20607,'Ndege Dispensary')
insert into [FacilityList] values(20645,'Truecare Medical Clinic')
insert into [FacilityList] values(20667,'Neighbours Medical Clinic Kabazi')
insert into [FacilityList] values(20679,'Eshikalame Dispensary')
insert into [FacilityList] values(20684,'Amaiga Dispensary (Manga)')
insert into [FacilityList] values(20685,'Della Dispensary')
insert into [FacilityList] values(20709,'Gunana Dispensary')
insert into [FacilityList] values(20723,'Iimbani Dispensary')
insert into [FacilityList] values(20725,'Lerds medical Clinic')
insert into [FacilityList] values(20737,'Nthungu Dispensary')
insert into [FacilityList] values(20749,'Ngiori Dispensary')
insert into [FacilityList] values(20755,'Seren Dispensary')
insert into [FacilityList] values(20756,'Urah Dispensary')
insert into [FacilityList] values(20757,'Parkati Dispensary')
insert into [FacilityList] values(20769,'Kikalu Dispensary')
insert into [FacilityList] values(20788,'Kai Dispensary')
insert into [FacilityList] values(20789,'Kalungu Dispensary')
insert into [FacilityList] values(20793,'Kasemeini Dispensary')
insert into [FacilityList] values(20794,'Kwakotoe Dispensary')
insert into [FacilityList] values(20795,'Nzouni Dispensary(Kaiti)')
insert into [FacilityList] values(20796,'Mbui-Nzau Dispensary')
insert into [FacilityList] values(20797,'Mithumoni Dispensary')
insert into [FacilityList] values(20798,'Nthongoni Dispensary')
insert into [FacilityList] values(20799,'Mikuyuni Dispensary (Kibwezi West)')
insert into [FacilityList] values(20801,'Kinyau Dispensary')
insert into [FacilityList] values(20802,'Nduuni Dispensary')
insert into [FacilityList] values(20805,'Muthingiini Dispensary')
insert into [FacilityList] values(20810,'Ngomano Dispensary')
insert into [FacilityList] values(20826,'Lorugum Sub County Hospital')
insert into [FacilityList] values(20835,'Bethania Medical Clinic')
insert into [FacilityList] values(20839,'Impact Health Care')
insert into [FacilityList] values(20842,'Kasitet Dispensary (Alale)')
insert into [FacilityList] values(20843,'Malichi Dispensary')
insert into [FacilityList] values(20853,'ZAC Medical Clinic')
insert into [FacilityList] values(20871,'Maemba Dispensary')
insert into [FacilityList] values(20880,'Marura Medical Centre-Eldoret')
insert into [FacilityList] values(20887,'Nakabosan Dispensary')
insert into [FacilityList] values(20922,'Kenya Community Health Network')
insert into [FacilityList] values(20932,'Kwawanzilu Disp')
insert into [FacilityList] values(20951,'Hubuini Dispensary')
insert into [FacilityList] values(20969,'Nzukini Dispensary(KAITI)')
insert into [FacilityList] values(20971,'Nyaani Dispensary(KAITI)')
insert into [FacilityList] values(20972,'Yandue Dispensary')
insert into [FacilityList] values(20973,'Utwiini Dispensary')
insert into [FacilityList] values(21006,'West Pokot County Beyond Zero Mobile Clinic')
insert into [FacilityList] values(21014,'Uasingishu County Beyond Zero Mobile Clinic')
insert into [FacilityList] values(21017,'Nakuru Beyond Zero Mobile Clinic')
insert into [FacilityList] values(21036,'Khajula Dispensay')
insert into [FacilityList] values(21037,'Busagwa Dispensary')
insert into [FacilityList] values(21051,'Kenlands Health Services Maili Sita')
insert into [FacilityList] values(21090,'Kapchesewes dispensary')
insert into [FacilityList] values(21109,'Itonguri Dispensary')
insert into [FacilityList] values(21115,'Mago Care Health Centre')
insert into [FacilityList] values(21119,'Mwapula Dispensary')
insert into [FacilityList] values(21166,'Doctors Worldwide Muallafatul Qulub Medical Centre')
insert into [FacilityList] values(21199,'Holy Family Childrens Home Dispensary')
insert into [FacilityList] values(21214,'Bogyar dispensary')
insert into [FacilityList] values(21256,'Gandini community dispensary')
insert into [FacilityList] values(21318,'Leeta Dispensary')
insert into [FacilityList] values(21374,'Moruangibuin Dispensary')
insert into [FacilityList] values(21388,'Nakoyo Dispensary')
insert into [FacilityList] values(21389,'Ekicheles Dispensary')
insert into [FacilityList] values(21391,'Riokomor Dispensary')
insert into [FacilityList] values(21392,'Epur Dispensary')
insert into [FacilityList] values(21449,'Maroba Dispensary')
insert into [FacilityList] values(21467,'Mothersolbrit Hospital')
insert into [FacilityList] values(21481,'Muanda Dispensary')
insert into [FacilityList] values(21483,'Mwikhupo Dispensary')
insert into [FacilityList] values(21488,'Odino Health Centre')
insert into [FacilityList] values(21489,'Awach Health Centre')
insert into [FacilityList] values(21491,'Harambee H/C')
insert into [FacilityList] values(21496,'Kaliati Dispensary')
insert into [FacilityList] values(21528,'Highway medical clinic')
insert into [FacilityList] values(21539,'Konjora Dispensary')
insert into [FacilityList] values(21540,'Shelter of Hope Medical clinic')
insert into [FacilityList] values(21544,'Jila Model Health Centre')
insert into [FacilityList] values(21545,'Kachororoni Dispensary')
insert into [FacilityList] values(21549,'Torochmoi Dispensary')
insert into [FacilityList] values(21550,'Kongnyalil Dispensary')
insert into [FacilityList] values(21551,'Kaprobu Dispensary')
insert into [FacilityList] values(21600,'Seguton Dispensary')
insert into [FacilityList] values(21601,'Chepkinoyiyo dispensary')
insert into [FacilityList] values(21604,'Masaita dispensary')
insert into [FacilityList] values(21605,'Choronok dispensary')
insert into [FacilityList] values(21608,'Talitia Dispensary')
insert into [FacilityList] values(21619,'Mewa Drop-In-Centre (Kilifi)')
insert into [FacilityList] values(21620,'Machakha Dispensary')
insert into [FacilityList] values(21678,'Jumupamozzi Medical Centre')
insert into [FacilityList] values(21694,'Kombani Dispensary')
insert into [FacilityList] values(21795,'Kochieng Dispensary')
insert into [FacilityList] values(21801,'Kithoni Dispensary')
insert into [FacilityList] values(21825,'Hadley dispensary Dispensary')
insert into [FacilityList] values(21854,'Kereria Dispensary')
insert into [FacilityList] values(21855,'Kirukuma Dispensary')
insert into [FacilityList] values(21913,'Usungu Dispensary')
insert into [FacilityList] values(21914,'Mwasangombe Dispenasry')
insert into [FacilityList] values(21915,'Matiku Dispensary')
insert into [FacilityList] values(21917,'Havilah Health Care')
insert into [FacilityList] values(21918,'Burudisha Medical Clinic')
insert into [FacilityList] values(21921,'Sokoke Imani Medical Clinic')
insert into [FacilityList] values(21944,'Busa dispensary')
insert into [FacilityList] values(21947,'Mwangoloto Dispensary')
insert into [FacilityList] values(22026,'Musumaa Disp')
insert into [FacilityList] values(22035,'Mikeu Dispensary')
insert into [FacilityList] values(22038,'Kiburuti Dispensary')
insert into [FacilityList] values(22159,'Good Shepherd Medical Clinic')
insert into [FacilityList] values(22190,'Kilusi Health Centre')
insert into [FacilityList] values(22228,'Nzalae Dispensary (Nguutani)')
insert into [FacilityList] values(22240,'Keynan Medical Clinic')
insert into [FacilityList] values(22242,'Anama Medical Clinic')
insert into [FacilityList] values(22273,'Maisha Medical Clinic')
insert into [FacilityList] values(22274,'Finecare Medical Clinic')
insert into [FacilityList] values(22277,'Dawood Health Care')
insert into [FacilityList] values(22278,'Wongonyi Dispensary')
insert into [FacilityList] values(22279,'The River Jordan Medical Centre')
insert into [FacilityList] values(22281,'Soweto Medical Centre')
insert into [FacilityList] values(22283,'Zonal Annex Nursing Home')
insert into [FacilityList] values(22284,'kanyadet Disp')
insert into [FacilityList] values(22285,'Solonamu medical centre')
insert into [FacilityList] values(22287,'Reach out Centre Trust')
insert into [FacilityList] values(22288,'Malukiloriti Dispensary')
insert into [FacilityList] values(22290,'OBAMA DISPENSARY')
insert into [FacilityList] values(22303,'ACK OTARO COMMUNITY DISPENSARY')
insert into [FacilityList] values(22308,'Kyumani Dispensary')
insert into [FacilityList] values(22314,'Kathekani dispensary')
insert into [FacilityList] values(22320,'LENMEK HOSPITAL RONGO ANNEX')
insert into [FacilityList] values(22324,'The Oak Health Centre')
insert into [FacilityList] values(22332,'Avenue Health  Care( Garden City Clinic )')
insert into [FacilityList] values(22334,'Iris Eye Clinic Kisumu')
insert into [FacilityList] values(22344,'Adoani Medical Services')
insert into [FacilityList] values(22345,'Maysparsube Health Services')
insert into [FacilityList] values(22346,'Grace Home Clinic')
insert into [FacilityList] values(22360,'Lolupe (Turkana West) Dispensary')
insert into [FacilityList] values(22362,'Kenyangaluk dispensary')
insert into [FacilityList] values(22371,'MFANGANO COMMUNITY HEALTH CENTREM')
insert into [FacilityList] values(22373,'Kreswo')
insert into [FacilityList] values(22374,'Komol Dispensary')
insert into [FacilityList] values(22379,'Kemunchugu Dispensary (Nyamira north)')
insert into [FacilityList] values(22382,'NYAMUSI MEDICAL CENTER')
insert into [FacilityList] values(22384,'St. Raphael')
insert into [FacilityList] values(22434,'Equity Afia m/c')
insert into [FacilityList] values(22489,'P.C.E.A Ruburi Medical Clinic')
insert into [FacilityList] values(22491,'Uvaani Dispensary')
insert into [FacilityList] values(22492,'GAENA')
insert into [FacilityList] values(22493,'RADHORE DISPENSARY')
insert into [FacilityList] values(22497,'Chitsanze Dispensary')
insert into [FacilityList] values(22498,'Uthanya Dispensary')
insert into [FacilityList] values(22499,'Olengo Dispensary')
insert into [FacilityList] values(22516,'Tinashe Medical Centre')
insert into [FacilityList] values(22517,'Kumpa Dispensary')
insert into [FacilityList] values(22521,'Transami Clinic')
insert into [FacilityList] values(22524,'Baraka Dispensary')
insert into [FacilityList] values(22525,'Mugumo Dispensary')
insert into [FacilityList] values(22526,'Ndovoini nguumo')
insert into [FacilityList] values(22529,'Nyamasaria Medical Clinic')
insert into [FacilityList] values(22530,'Ager community dispensary')
insert into [FacilityList] values(22531,'mawego community medical centre')
insert into [FacilityList] values(22532,'Okita Health Center')
insert into [FacilityList] values(22533,'Alaro community dispensary')
insert into [FacilityList] values(22535,'Green View MC')
insert into [FacilityList] values(22539,'AFYA MASHINANI MEDICAL CENTRE GACHAMI')
insert into [FacilityList] values(22540,'Sawa Sawa Health Services')
insert into [FacilityList] values(22542,'Oasis Mission Hospital')
insert into [FacilityList] values(22543,'Lake Kanyaboli Community Dispensary')
insert into [FacilityList] values(22552,'Loyal Care Medical Centre')
insert into [FacilityList] values(22553,'Benard Vision Medical Center')
insert into [FacilityList] values(22558,'Afya Kimbilio Medical Clinic')
insert into [FacilityList] values(22559,'Joamu Medical Clinic')
insert into [FacilityList] values(22560,'Trinity Mission clinic')
insert into [FacilityList] values(22561,'ST. Francis Moto Hope Dispensary')
insert into [FacilityList] values(22562,'Avenue Health Care Embakasi')
insert into [FacilityList] values(22563,'Chavogere Dispensary')
insert into [FacilityList] values(22564,'Tumaini Dice')
insert into [FacilityList] values(22583,'Kapsigilai')
insert into [FacilityList] values(22584,'Kesogon')
insert into [FacilityList] values(22585,'SINDO MEDICAL CENTRE')
insert into [FacilityList] values(22587,'St. Annes Medical Clinic')
insert into [FacilityList] values(22590,'GINGO COMMUNITY')
insert into [FacilityList] values(22591,'Cheptobot')
insert into [FacilityList] values(22592,'Dr.Stephen Kamore Wanjohi')
insert into [FacilityList] values(22594,'Aruba')
insert into [FacilityList] values(22598,'Mercal Health Care Ltd')
insert into [FacilityList] values(22599,'Chanuka Youth Centre')
insert into [FacilityList] values(22600,'Saboti Medical Clinic')
insert into [FacilityList] values(22601,'Bwake')
insert into [FacilityList] values(22604,'Oloolakir Disoensary')
insert into [FacilityList] values(22611,'Gidagadi dispensary')
insert into [FacilityList] values(22618,'St.Claire Medical Clinic')
insert into [FacilityList] values(22621,'Worldpharm Clinic')
insert into [FacilityList] values(22624,'Rafiki Health Centre')
insert into [FacilityList] values(22625,'MAISHA HEALTH CARE CLINIC')
insert into [FacilityList] values(22626,'Chemichem Dispensary')
insert into [FacilityList] values(22628,'Koykoy Dispensary')
insert into [FacilityList] values(22633,'Gekonge Dispensary')
insert into [FacilityList] values(22638,'Yuni Medical Clinic')
insert into [FacilityList] values(22639,'Africare Ltd Karen Clinic')
insert into [FacilityList] values(22641,'Keringet Medical Centre')
insert into [FacilityList] values(22646,'St. Peters and Ann Medical Centre')
insert into [FacilityList] values(22648,'Primecare medical centre')
insert into [FacilityList] values(22649,'Sirende medical clinic')
insert into [FacilityList] values(22650,'Lwenya Dispensary')
insert into [FacilityList] values(22651,'CENTRAL MEDICAL CLINIC')
insert into [FacilityList] values(22653,'Jebrok Dispensary')
insert into [FacilityList] values(22660,'Runogone Dispensary')
insert into [FacilityList] values(22664,'Kapkitony')
insert into [FacilityList] values(22665,'Cheptul CFC Community Health Centre')
insert into [FacilityList] values(22666,'Gambogi Medical Centre')
insert into [FacilityList] values(22667,'machesa dispensary')
insert into [FacilityList] values(22671,'Kimathi Healthcare medical clinic')
insert into [FacilityList] values(22673,'Professor Wasuna Clinic')
insert into [FacilityList] values(22677,'Mwangea community Dispensary')
insert into [FacilityList] values(22678,'Masii Medical Centre')
insert into [FacilityList] values(22679,'Mtwapa drop in and resource centre')
insert into [FacilityList] values(22681,'Tumaini CFW Clinic')
insert into [FacilityList] values(22682,'Medicross Hospital')
insert into [FacilityList] values(22683,'Patience CFW Clinic')
insert into [FacilityList] values(22684,'Faith CFW Clinic')
insert into [FacilityList] values(22688,'St. Akidiva Memorial')
insert into [FacilityList] values(22689,'Gathumbi Dispensary')
insert into [FacilityList] values(22690,'Kianjogu Dispensary')
insert into [FacilityList] values(22692,'Cieni dispensary')
insert into [FacilityList] values(22693,'KIAGUTHU DISPENSARY')
insert into [FacilityList] values(22694,'MAISHA CLINIC NDHIWA')
insert into [FacilityList] values(22695,'MAMAS NURSING HOME')
insert into [FacilityList] values(22700,'Divine Medical Clinic')
insert into [FacilityList] values(22702,'Wananchi Clinic and Optician')
insert into [FacilityList] values(22703,'Gakurwe Health Services')
insert into [FacilityList] values(22704,'Togonye Dispensary')
insert into [FacilityList] values(22740,'Afya Bora Clinic(Busia)')
insert into [FacilityList] values(22741,'Wellness Medical Clinic (Riabai )')
insert into [FacilityList] values(22742,'Maombolea Peer Empowerment Group(MPEG)')
insert into [FacilityList] values(22743,'Alpha Links Medical Clinic')
insert into [FacilityList] values(22744,'KOTIENDE OUPATIENT CLINIC')
insert into [FacilityList] values(22747,'OTIENDE OUTPATIENT CLINIC')
insert into [FacilityList] values(22748,'Get Well Clinic')
insert into [FacilityList] values(22750,'Caremax Health Services')
insert into [FacilityList] values(22751,'A.I.P.C.A Nakuru West Medical Centre')
insert into [FacilityList] values(22752,'Lwakhakha Dispensary')
insert into [FacilityList] values(22753,'Ruai Family Hospital - Tala')
insert into [FacilityList] values(22754,'Eastern Afya Medical Centre')
insert into [FacilityList] values(22755,'Bahati Hospital - Malaa')
insert into [FacilityList] values(22757,'Lukanji Dispensary')
insert into [FacilityList] values(22758,'Eregi Teachers Training College Clinic')
insert into [FacilityList] values(22759,'Shirumba Dispensary')
insert into [FacilityList] values(22760,'Kikopey Dispensary')
insert into [FacilityList] values(22762,'Hope care medical centre')
insert into [FacilityList] values(22763,'Fairview Nursing Home')
insert into [FacilityList] values(22764,'Rungut Dispensary')
insert into [FacilityList] values(22766,'Jimba Dispensary')
insert into [FacilityList] values(22768,'Bliss M Clinic')
insert into [FacilityList] values(22770,'Lifecare Hospitals Ltd')
insert into [FacilityList] values(22771,'St. Joseph Catholic dipensary Maungu')
insert into [FacilityList] values(22773,'HEARTLANDS MEDICAL CENTRE')
insert into [FacilityList] values(22775,'Bethlehem Home Hospital')
insert into [FacilityList] values(22776,'st Angela Medical Centre')
insert into [FacilityList] values(22777,'Blissfam medical centre')
insert into [FacilityList] values(22778,'Rushi Medical Clinic')
insert into [FacilityList] values(22779,'Lomunyenekirionok dispensary')
insert into [FacilityList] values(22780,'Uzima Care Medical Clinic')
insert into [FacilityList] values(22783,'Malombe Dispensary')
insert into [FacilityList] values(22784,'Equity Afia Kayole')
insert into [FacilityList] values(22785,'Gertrudes Children Hospital-Thika Rd')
insert into [FacilityList] values(22788,'Agahkan Ngong Clinic')
insert into [FacilityList] values(22789,'Chepsoo Medical Centre')
insert into [FacilityList] values(22790,'Smilestar Medical Services &Dental Care')
insert into [FacilityList] values(22791,'Equity Afia Kawangware')
insert into [FacilityList] values(22795,'Holsoms Nursing Home')
insert into [FacilityList] values(22802,'Maisha Masha  Dispensary')
insert into [FacilityList] values(22803,'Sinambio Disp')
insert into [FacilityList] values(22804,'Tewe Dispensary')
insert into [FacilityList] values(22805,'South C Dialysis Centre')
insert into [FacilityList] values(22806,'Dago')
insert into [FacilityList] values(22807,'Kiboswa medical clinic')
insert into [FacilityList] values(22808,'Uziwa Dispensary')
insert into [FacilityList] values(22811,'Ali Juja Hope Medical Centre')
insert into [FacilityList] values(22812,'Katsakakairu Disp')
insert into [FacilityList] values(22814,'Quality care medical clinic')
insert into [FacilityList] values(22815,'Gynocare womens &fistula hospital')
insert into [FacilityList] values(22817,'Mwana Dispensary')
insert into [FacilityList] values(22818,'Kituluku Dispensary')
insert into [FacilityList] values(22822,'Kasunguni Dispensary(KAITI)')
insert into [FacilityList] values(22824,'Kathongo Dispensary')
insert into [FacilityList] values(22826,'Kivani  Dispensary (Mbooni)')
insert into [FacilityList] values(22828,'Nasianda')
insert into [FacilityList] values(22833,'kwa Kakulu Dispensary (Emali)')
insert into [FacilityList] values(22834,'Makasa Dispensary (Nguu)')
insert into [FacilityList] values(22835,'Bestcare Medical and diagnostic centre ltd- Emali')
insert into [FacilityList] values(22836,'Our Mother of Perpetual Help Bamba Catholic Dispensary')
insert into [FacilityList] values(22838,'Neema Medical Clinic')
insert into [FacilityList] values(22839,'MARBLE HEALTHCARE LIMITED')
insert into [FacilityList] values(22841,'COUNTY MEDICARE LIMITED')
insert into [FacilityList] values(22842,'Medicross Limited Langata Mall(Mugumoini)')
insert into [FacilityList] values(22843,'SIMBA CLINIC ISIOLO')
insert into [FacilityList] values(22844,'South C Hospital Limited(South C)')
insert into [FacilityList] values(22845,'HEALTH PACT')
insert into [FacilityList] values(22847,'GITURA DISP')
insert into [FacilityList] values(22849,'Patema Medical Clinic')
insert into [FacilityList] values(22850,'Karen Roses Medical Clinic')
insert into [FacilityList] values(22851,'Oasis Doctors Plaza Nairobi Green House')
insert into [FacilityList] values(22853,'Naagis Dispensary')
insert into [FacilityList] values(22855,'Selinas Health Care')
insert into [FacilityList] values(22857,'Saika Community Medical Centre')
insert into [FacilityList] values(22859,'Mercy Mission Hospital - Annex Nakuru')
insert into [FacilityList] values(22860,'Aimo Dispensary')
insert into [FacilityList] values(22861,'Stom Medical Centre')
insert into [FacilityList] values(22862,'ScanHealth Limited-Kericho')
insert into [FacilityList] values(22865,'Mbaru GOK Disp.')
insert into [FacilityList] values(22866,'Africare Ltd NHIF clinic')
insert into [FacilityList] values(22867,'Africare Ltd Forts building')
insert into [FacilityList] values(22868,'Mzedu Clinic')
insert into [FacilityList] values(22869,'Helmon clinic&lab services')
insert into [FacilityList] values(22874,'mogindo dispensary')
insert into [FacilityList] values(22875,'RUIRU  FAMILY CLINIC')
insert into [FacilityList] values(22877,'SIMIT DISPENSARY')
insert into [FacilityList] values(22878,'shidley dispensary')
insert into [FacilityList] values(22879,'ATIMIROS MEMORIAL')
insert into [FacilityList] values(22880,'KIRIMA NDUNGIRI DISPENSARY')
insert into [FacilityList] values(22881,'AFYA MEDICAL CLINIC')
insert into [FacilityList] values(22884,'Masaani Dispensary')
insert into [FacilityList] values(22885,'Bliss GVS Health Care Limited (Machakos)')
insert into [FacilityList] values(22886,'Alexandria Cancer Centre & Palliative care Hospital')
insert into [FacilityList] values(22887,'Afya Link Medical Center')
insert into [FacilityList] values(22888,'Mwea Capital Medical Center')
insert into [FacilityList] values(22889,'Sanctuary Rains Medical Centre')
insert into [FacilityList] values(22890,'Medanta AfriCare')
insert into [FacilityList] values(22895,'Kilele Medical Specialist Centre')
insert into [FacilityList] values(22896,'St. Patricks nursing home')
insert into [FacilityList] values(22898,'COMMUNITY HEALTH SERVICE')
insert into [FacilityList] values(22899,'Orion Healthcare Medical Centre')
insert into [FacilityList] values(22900,'Kericho Medical Clinic')
insert into [FacilityList] values(22901,'Dawida Medical Centre')
insert into [FacilityList] values(22902,'Kauti Dispensary')
insert into [FacilityList] values(22903,'Johry Medical Centre')
insert into [FacilityList] values(22904,'ST.TRESAS OLK MEDICAL CLINIC')
insert into [FacilityList] values(22905,'Muthangira Dispensary')
insert into [FacilityList] values(22906,'Olympus Medical Clinic')
insert into [FacilityList] values(22907,'Gemifa Medical Clinic')
insert into [FacilityList] values(22908,'Musuani Medical Centre')
insert into [FacilityList] values(22909,'Elephant Dental LTD-Kericho Clinic')
insert into [FacilityList] values(22910,'Mukuthu Dispensary')
insert into [FacilityList] values(22911,'Yalatani Dispensary')
insert into [FacilityList] values(22912,'Gates of Hope Family Medicare centre')
insert into [FacilityList] values(22913,'Family Medical Clinic(Machakos)')
insert into [FacilityList] values(22914,'Enzai Dispensary')
insert into [FacilityList] values(22915,'AVENUE HEALTHCARE GREENSPAN')
insert into [FacilityList] values(22916,'Africare Limited Embakasi Clinic')
insert into [FacilityList] values(22918,'Itoleka Smartext Medical Services')
insert into [FacilityList] values(22919,'Total Health Dispensary(Naivasha)')
insert into [FacilityList] values(22920,'Baraka')
insert into [FacilityList] values(22922,'ST.TERESA ASANTE NAGOYA DISPENSARY')
insert into [FacilityList] values(22923,'VINE MEDICAL CLINIC')
insert into [FacilityList] values(22924,'Clastan medical services')
insert into [FacilityList] values(22925,'Mt. Kenya medical clinic')
insert into [FacilityList] values(22926,'Alliance Medical Centre (Mombasa)')
insert into [FacilityList] values(22927,'PREMIERCARE DIAGNOSTICS NAROK LIMITED')
insert into [FacilityList] values(22928,'Kaiti Dispensary')
insert into [FacilityList] values(22929,'Njoguini')
insert into [FacilityList] values(22930,'Mbogoini')
insert into [FacilityList] values(22931,'Matuiku')
insert into [FacilityList] values(22933,'Maili Saba')
insert into [FacilityList] values(22934,'THE MAZIRA MEMORIAL HOSPITAL')
insert into [FacilityList] values(22935,'Margaret Njoki Memorial Health Centre LTD.')
insert into [FacilityList] values(22936,'NAMUNYAK MEDICAL CENTRE')
insert into [FacilityList] values(22937,'Afya Medical Ngambo Clinic')
insert into [FacilityList] values(22938,'The Mater Hospital-Satelite Clinic(TRM)')
insert into [FacilityList] values(22939,'Masaani Dispensary Yatta')
insert into [FacilityList] values(22940,'Makila Dispensary Yatta')
insert into [FacilityList] values(22941,'Kalukuni Dispensary Yatta')
insert into [FacilityList] values(22942,'NYS Athiriver Yatta')
insert into [FacilityList] values(22943,'Kiwanza Dispensary Yatta')
insert into [FacilityList] values(22944,'Kalyambeu Dispensary Yatta')
insert into [FacilityList] values(22945,'Kaluluini Dispensary Yatta')
insert into [FacilityList] values(22946,'Penda Medical Care-Kahawa West')
insert into [FacilityList] values(22947,'Vision Express Optician')
insert into [FacilityList] values(22948,'Nazareth Medical Services-Githurai')
insert into [FacilityList] values(22949,'George Mudenyo Kadima Nasio Trust (Mumias West)')
insert into [FacilityList] values(22950,'Powys Dispensary')
insert into [FacilityList] values(22954,'Kiani Kia Etama Dispensary')
insert into [FacilityList] values(22955,'Mbulutini Dispensary')
insert into [FacilityList] values(22962,'Rangwe Hometown Medical Clinic')
insert into [FacilityList] values(22963,'Ankara Medical Centre')
insert into [FacilityList] values(22964,'Iriamurai Dispensary')
insert into [FacilityList] values(22965,'Bristol Park Hospital(Machakos)')
insert into [FacilityList] values(22966,'St.Anns Catholic Dispensary Kapsorok')
insert into [FacilityList] values(22967,'Vital Solutions Health Centre')
insert into [FacilityList] values(22968,'Emayian Medical Clinic')
insert into [FacilityList] values(22969,'KANCO Drop in Centre')
insert into [FacilityList] values(22970,'MOUNT OLIVE MEDICAL CENTRE')
insert into [FacilityList] values(22971,'Songot Medical Clinic')
insert into [FacilityList] values(22972,'Sweetwaters Serena Clinic')
insert into [FacilityList] values(22974,'Bonde dispensary')
insert into [FacilityList] values(22975,'Angogo dispensary')
insert into [FacilityList] values(22976,'RADIANT GROUP OF HOSPITALS-UMOJA')
insert into [FacilityList] values(22977,'Fairview Medical Clinic')
insert into [FacilityList] values(22978,'Mugie Conservancy Dispensary')
insert into [FacilityList] values(22980,'Kangeso Dispensary')
insert into [FacilityList] values(22982,'Tamba Pwani - Kilifi')
insert into [FacilityList] values(22985,'KOPANGA DISPENSARY')
insert into [FacilityList] values(22988,'KABONGO COMMUNITY HEALTH CENTRE')
insert into [FacilityList] values(22989,'Mombasa Huduma Center VCT Site')
insert into [FacilityList] values(22990,'Smart Healthcare Maai Mahiu')
insert into [FacilityList] values(22992,'Mituvu Dispensary')
insert into [FacilityList] values(22993,'EGETUKI MEDICAL CLINIC')
insert into [FacilityList] values(22996,'Jambo Medical Centre')
insert into [FacilityList] values(22997,'Makutano Family Health Care Services')
insert into [FacilityList] values(22998,'Kaka Medical Clinic')
insert into [FacilityList] values(22999,'Kituni Dispensary')
insert into [FacilityList] values(23000,'Pemba Medicare  Kangeta')
insert into [FacilityList] values(23001,'Indopa Medical Clinic')
insert into [FacilityList] values(23002,'Joyland F Clinic Tassia')
insert into [FacilityList] values(23003,'Lelechwet')
insert into [FacilityList] values(23004,'Jamii Bora Medical Clinic')
insert into [FacilityList] values(23005,'Ico Care  Health Clinic')
insert into [FacilityList] values(23006,'Kamahuha MC')
insert into [FacilityList] values(23007,'Bishop Morrow Disp')
insert into [FacilityList] values(23008,'Kagaa Disp')
insert into [FacilityList] values(23009,'Gikomora Disp')
insert into [FacilityList] values(23011,'Kwa Kamau MC')
insert into [FacilityList] values(23013,'ikalaasa dispensary')
insert into [FacilityList] values(23014,'Kiti Kyumu Dispensary')
insert into [FacilityList] values(23016,'yikiuuku dispensary')
insert into [FacilityList] values(23018,'Mandoi Dispensary')
insert into [FacilityList] values(23019,'Bosnia Dispensary')
insert into [FacilityList] values(23021,'Potter`s Family Hospital')
insert into [FacilityList] values(23023,'Canaan Medical clinic')
insert into [FacilityList] values(23024,'SALAMED')
insert into [FacilityList] values(23025,'Antubetwe Kiongo Integrated Clinic')
insert into [FacilityList] values(23026,'KABIANGEK DISPENSARY')
insert into [FacilityList] values(23027,'CHEMELET DISPENSARY')
insert into [FacilityList] values(23028,'Bliss Gvs Health Care Ltd (Kericho)')
insert into [FacilityList] values(23029,'Runda medical health service')
insert into [FacilityList] values(23030,'Zombe Hospital')
insert into [FacilityList] values(23031,'Arise  Hospital  Limited')
insert into [FacilityList] values(23032,'Mac Dental clinic')
insert into [FacilityList] values(23033,'Kamuwongo Hope Medicare Centre')
insert into [FacilityList] values(23034,'Tai medical centre')
insert into [FacilityList] values(23035,'Straight Smile Dental Ltd')
insert into [FacilityList] values(23036,'MediHealth Investment Group Ltd(Kericho)')
insert into [FacilityList] values(23037,'Rapha Medicare Centre Matunda')
insert into [FacilityList] values(23038,'Boma Medicare')
insert into [FacilityList] values(23039,'Meka Medical Clinic')
insert into [FacilityList] values(23041,'Dr.Joy P.Mpaata')
insert into [FacilityList] values(23042,'Millenium Medical Clinic')
insert into [FacilityList] values(23044,'Trinity opticals Limited')
insert into [FacilityList] values(23045,'Majaoni Healthcare Clinic')
insert into [FacilityList] values(23046,'Ideal Hope Medical Clinic')
insert into [FacilityList] values(23047,'Afyacare health services')
insert into [FacilityList] values(23048,'Mosop Dispensary')
insert into [FacilityList] values(23049,'Ivory Health Solutions Limited')
insert into [FacilityList] values(23050,'Nimoli Medical Services Fedha')
insert into [FacilityList] values(23051,'South Kinangop Medical Clinic')
insert into [FacilityList] values(23052,'Shelly Health Care Services')
insert into [FacilityList] values(23053,'Shelly Beach Hospital')
insert into [FacilityList] values(23054,'Jubilee Medical  Clinic')
insert into [FacilityList] values(23055,'SHAMMAH HEALTH SERVICES')
insert into [FacilityList] values(23056,'Mwala Medical Clinic Medical Clinic')
insert into [FacilityList] values(23057,'Ponya Medal  Clinic')
insert into [FacilityList] values(23058,'Bliss GVS Embakasi Clinic')
insert into [FacilityList] values(23059,'Namuya Shalom Medical Services')
insert into [FacilityList] values(23060,'RAFIKI MED CLINIC')
insert into [FacilityList] values(23061,'Starshine  Medical  Centre')
insert into [FacilityList] values(23062,'Medirex  Medical  Services')
insert into [FacilityList] values(23063,'Guardian Medical  Services')
insert into [FacilityList] values(23064,'Miritini Medical Clinic')
insert into [FacilityList] values(23065,'Mutunga Diagnostic center limited')
insert into [FacilityList] values(23066,'Horizon Medicare')
insert into [FacilityList] values(23067,'KARAA DISPENSARY')
insert into [FacilityList] values(23068,'Radiant Hospital Kasarani Annex')
insert into [FacilityList] values(23069,'Rajuera Dispensary')
insert into [FacilityList] values(23070,'Losibil dispensary')
insert into [FacilityList] values(23071,'Koimugul Dispensary')
insert into [FacilityList] values(23072,'Family Bora medical center')
insert into [FacilityList] values(23075,'KIANGANDA DISPENSARY')
insert into [FacilityList] values(23076,'PRECISION COUNSELING HOME')
insert into [FacilityList] values(23077,'Dwinsac Clinic')
insert into [FacilityList] values(23079,'Kagaaa Dispensary')
insert into [FacilityList] values(23080,'Naivasha Quality Health Care Services LTD(Karagita)')
insert into [FacilityList] values(23081,'Karemaini Dispensary')
insert into [FacilityList] values(23083,'Kathera Medical Services')
insert into [FacilityList] values(23084,'Kaptuya dispensary')
insert into [FacilityList] values(23085,'Mulata Dispensary')
insert into [FacilityList] values(23086,'West Ngosini Dispensary')
insert into [FacilityList] values(23087,'Fahelma community CFW Clinic')
insert into [FacilityList] values(23088,'Haifa Medical Centre')
insert into [FacilityList] values(23089,'Penda Medical  Clinic')
insert into [FacilityList] values(23091,'Hum Medical Clinic')
insert into [FacilityList] values(23092,'Manyonge')
insert into [FacilityList] values(23093,'Medical Spiral')
insert into [FacilityList] values(23094,'MUCHARAGE DISPENSARY')
insert into [FacilityList] values(23095,'Nairobi Place Addiction Treatment Centre Tumaini Ltd (Karen)')
insert into [FacilityList] values(23097,'Nairobi Place Treatment Centre Tumaini Ltd')
insert into [FacilityList] values(23098,'Palmed Healthcare')
insert into [FacilityList] values(23099,'St. Merryl Medical Services')
insert into [FacilityList] values(23100,'AJ Clinic')
insert into [FacilityList] values(23102,'By Grace Medical Clinic Kisasi')
insert into [FacilityList] values(23103,'Salama Medical Clinic')
insert into [FacilityList] values(23104,'Focus Clinical and Diagnostic Center')
insert into [FacilityList] values(23105,'Muchorwi Medical Clinic')
insert into [FacilityList] values(23107,'Jema Medical Clinic')
insert into [FacilityList] values(23108,'Shamakhokho Neema medical clinic')
insert into [FacilityList] values(23116,'Masimba medicare centre')
insert into [FacilityList] values(23118,'Shakahola Dispensary')
insert into [FacilityList] values(23121,'Kamale Dispensary')
insert into [FacilityList] values(23123,'Josta Medical Centre')
insert into [FacilityList] values(23124,'Kwale District Eye Centre')
insert into [FacilityList] values(23126,'Mbwaleni Dispensry')
insert into [FacilityList] values(23127,'Mbegani Dispensary')
insert into [FacilityList] values(23128,'Mwena')
insert into [FacilityList] values(23129,'Bilashaka Dispensary')
insert into [FacilityList] values(23130,'Afya Bora Medical Clinic')
insert into [FacilityList] values(23131,'Sisters of St. Josepth Catholic Dispensary')
insert into [FacilityList] values(23132,'Pongwe/Kidimu Dispensary')
insert into [FacilityList] values(23133,'Vwivwini Dispensary')
insert into [FacilityList] values(23134,'Mtumwa Dispensary')
insert into [FacilityList] values(23135,'Pangani Dispensary (Lungalunga)')
insert into [FacilityList] values(23137,'Mainland Relief Hospital')
insert into [FacilityList] values(23138,'Samao Medical Clinic')
insert into [FacilityList] values(23139,'Nakuru eye and optical clinic')
insert into [FacilityList] values(23140,'Thome Disp.')
insert into [FacilityList] values(23141,'Kwa Mbwiria Medical Clinic')
insert into [FacilityList] values(23142,'Family Solution M edical Centre')
insert into [FacilityList] values(23143,'Medicross Medical Clinic (Meru)')
insert into [FacilityList] values(23144,'Nem Medical Clinic')
insert into [FacilityList] values(23145,'Gatundu Womens medical Clinic')
insert into [FacilityList] values(23146,'Westmed Centre')
insert into [FacilityList] values(23147,'Kapsabet Eye Care')
insert into [FacilityList] values(23148,'Maua Family Medical Clinic')
insert into [FacilityList] values(23149,'Kilifi Dental Centre')
insert into [FacilityList] values(23150,'St Rael Home Care')
insert into [FacilityList] values(23156,'LANGA LANGA DISPENSARY')
insert into [FacilityList] values(23157,'Butieli Dispensary')
insert into [FacilityList] values(23158,'Summit MC (Nyansiongo)')
insert into [FacilityList] values(23159,'Summit MC (Chepilat)')
insert into [FacilityList] values(23160,'Bar Ober Medical Services')
insert into [FacilityList] values(23162,'Neema Digital Health Solutions(nzangathi)')
insert into [FacilityList] values(23164,'Royal Medical Center Clinic')
insert into [FacilityList] values(23166,'Mwobia Medical Clinic')
insert into [FacilityList] values(23167,'Kims Uzima Clinic')
insert into [FacilityList] values(23169,'LakeSide Integrated Medical Services(Naivasha)')
insert into [FacilityList] values(23171,'Esna Medical Clinic')
insert into [FacilityList] values(23178,'Tropical Medical Kakamega')
insert into [FacilityList] values(23179,'Muchiri Medical Clinic')
insert into [FacilityList] values(23182,'Mona Dispensary')
insert into [FacilityList] values(23183,'Takaba Nursing Home LTD')
insert into [FacilityList] values(23185,'Matagatani Dispensary')
insert into [FacilityList] values(23188,'Kalmba Health Care Centre')
insert into [FacilityList] values(23189,'Africare Ltd - TRM')
insert into [FacilityList] values(23190,'Partners For Care Medical Centre')
insert into [FacilityList] values(23191,'Riontonyi Dispensary')
insert into [FacilityList] values(23192,'Kambini Disp.')
insert into [FacilityList] values(23195,'Riamoni disp')
insert into [FacilityList] values(23196,'Emenyenche Dispensary')
insert into [FacilityList] values(23197,'Nyakegogi Disp.')
insert into [FacilityList] values(23198,'Kianungu Dispensary(MANGA')
insert into [FacilityList] values(23199,'Taita Dispensary')
insert into [FacilityList] values(23200,'bar Hostess Empowerment & Support programme-Roysambu')
insert into [FacilityList] values(23201,'HAVEN HOSPITAL')
insert into [FacilityList] values(23202,'LESSOS MEDICAL CLINIC')
insert into [FacilityList] values(23203,'LELWAK MEDICAL CLINIC')
insert into [FacilityList] values(23204,'AIC Kijabe Hospital Nairobi Medical Centre')
insert into [FacilityList] values(23205,'Immanuel Medical Clinic')
insert into [FacilityList] values(23211,'Doctors Plaza Garissa')
insert into [FacilityList] values(23212,'Ihiga dispensary')
insert into [FacilityList] values(23214,'Mathioya Medical Clinic')
insert into [FacilityList] values(23215,'Jocham Community Clinic Mtwapa')
insert into [FacilityList] values(23217,'Mama Rael Memorial Health Centre')
insert into [FacilityList] values(23218,'Kaathi Dipensary')
insert into [FacilityList] values(23222,'Medicross Clinic')
insert into [FacilityList] values(23223,'Medicross Clinic Megacity')
insert into [FacilityList] values(23224,'Cancer Care Kenya')
insert into [FacilityList] values(23226,'The International Clinic')
insert into [FacilityList] values(23227,'Ebenezer Medical Clinic')
insert into [FacilityList] values(23228,'Quality Medical Care')
insert into [FacilityList] values(23229,'Grawin Medical Clinic')
insert into [FacilityList] values(23230,'Gulumuse Dental Centre')
insert into [FacilityList] values(23231,'Bakari Medical Clinic')
insert into [FacilityList] values(23232,'Thika Annanas Medicross Clinic')
insert into [FacilityList] values(23234,'Alpha')
insert into [FacilityList] values(23235,'Kirinyaga optical and Healthcare')
insert into [FacilityList] values(23236,'Ngomannex Medcare Clinic')
insert into [FacilityList] values(23241,'Medicross Embu')
insert into [FacilityList] values(23244,'Busle Nursing Home')
insert into [FacilityList] values(23245,'Platinum Healthcare services limited')
insert into [FacilityList] values(23246,'The Mandera Hospital')
insert into [FacilityList] values(23247,'Geokings unique medical clinic')
insert into [FacilityList] values(23248,'Awenasa Medical Clinic')
insert into [FacilityList] values(23253,'Mwisho wa Lami Dispensary')
insert into [FacilityList] values(23254,'Medilink plus clinic- Rongai Nakuru')
insert into [FacilityList] values(23255,'St.Camillah clinic')
insert into [FacilityList] values(23257,'Lans Medical Clinics')
insert into [FacilityList] values(23258,'Nakuru Conventional Medical clinic')
insert into [FacilityList] values(23259,'Mwananchi medical Clinic')
insert into [FacilityList] values(23261,'New Point Medical Centre')
insert into [FacilityList] values(23262,'Mois. Bridge Medical Centre Likuyani')
insert into [FacilityList] values(23264,'Kwa Songe Dispensary')
insert into [FacilityList] values(23266,'Friends Medical Clinic Matunda')
insert into [FacilityList] values(23270,'Fino Nursing Home Limited')
insert into [FacilityList] values(23271,'Guardian Family Care Likuyani')
insert into [FacilityList] values(23272,'Lafey Care Nursing Home')
insert into [FacilityList] values(23273,'Chepsoo Medical Centre Tinderet')
insert into [FacilityList] values(23274,'Northgate Nursing Home')
insert into [FacilityList] values(23275,'Thagana County Medical Centre')
insert into [FacilityList] values(23276,'Kirimachuma APLSC Dispensara')
insert into [FacilityList] values(23277,'Kisumo Medical Centre')
insert into [FacilityList] values(23278,'Afya Health Essentials Kangari')
insert into [FacilityList] values(23279,'REHEAL MEDICAL CLINIC')
insert into [FacilityList] values(23280,'St. Merryl')
insert into [FacilityList] values(23282,'The Avenue Medical And Diagnostic Centre (Mikinduri)')
insert into [FacilityList] values(23283,'Al Manar Nursing Home')
insert into [FacilityList] values(23284,'Saphire Healthcare Nursing Home')
insert into [FacilityList] values(23285,'Chaani Catholic CBHC')
insert into [FacilityList] values(23288,'Reale Hospital Clinic')
insert into [FacilityList] values(23289,'Nelion Doctors Plaza')
insert into [FacilityList] values(23290,'St. Pauls Dawa Medical clinic')
insert into [FacilityList] values(23291,'Sky Medical Center')
insert into [FacilityList] values(23292,'Pevlink Services Ltd')
insert into [FacilityList] values(23293,'Polycare Medical Clinic')
insert into [FacilityList] values(23294,'Stadium Medical Clinic')
insert into [FacilityList] values(23297,'Kabete Gardens Hospital')
insert into [FacilityList] values(23298,'Plan Med Health Services')
insert into [FacilityList] values(23300,'MIRAJ2')
insert into [FacilityList] values(23301,'Cheboin Community Medical Clinic')
insert into [FacilityList] values(23302,'Albertol Medicare')
insert into [FacilityList] values(23303,'Maraba Pharmacy Clinic')
insert into [FacilityList] values(23304,'Utange Medical Centre')
insert into [FacilityList] values(23305,'Nyali Bridge Hospital')
insert into [FacilityList] values(23308,'Eastgate Medical Centre')
insert into [FacilityList] values(23309,'Joscare Medical Clinic')
insert into [FacilityList] values(23310,'Alfatah')
insert into [FacilityList] values(23312,'Chanzou Dispensary')
insert into [FacilityList] values(23314,'Ndoroto Dispensary')
insert into [FacilityList] values(23315,'IMARAH')
insert into [FacilityList] values(23316,'Partners In Life Support Health Services (KARIAMU)')
insert into [FacilityList] values(23317,'Kayole Dispensary')
insert into [FacilityList] values(23322,'Ganja La Simba')
insert into [FacilityList] values(23323,'Mvindeni')
insert into [FacilityList] values(23326,'Phense Medical Clinic')
insert into [FacilityList] values(23327,'Ahero Annex Healthcare Ltd')
insert into [FacilityList] values(23328,'Good Shepherd Life Care Centre(Embu)')
insert into [FacilityList] values(23329,'St.Augustine CFW Clinic(Embu)')
insert into [FacilityList] values(23331,'St.Teresa Cfw Clinic')
insert into [FacilityList] values(23334,'Star General Medical Centre')
insert into [FacilityList] values(23335,'Githuya DisGpensary')
insert into [FacilityList] values(23336,'Primex Medical Clinic')
insert into [FacilityList] values(23338,'Medisprings Medical Centre')
insert into [FacilityList] values(23339,'Akaiga Dispensary')
insert into [FacilityList] values(23340,'Goodlife Medical Centre Kambu')
insert into [FacilityList] values(23341,'Karamah Medical Clinic')
insert into [FacilityList] values(23342,'Mama Asha Nursing Home')
insert into [FacilityList] values(23343,'Devans Medical clinic')
insert into [FacilityList] values(23344,'Neo Solution Medical Center')
insert into [FacilityList] values(23346,'Sunrise Medical Clinic')
insert into [FacilityList] values(23347,'Rinpentiken Clinic')
insert into [FacilityList] values(23348,'Karama Medical Clinic')
insert into [FacilityList] values(23349,'Destiny Medical Centre')
insert into [FacilityList] values(23350,'Mother and Child Medical Clinic')
insert into [FacilityList] values(23351,'Liban Chemist and Optical Services')
insert into [FacilityList] values(23353,'Bushira Medical centre')
insert into [FacilityList] values(23354,'Jeka Health Care')
insert into [FacilityList] values(23355,'Lucys Medical Clinic')
insert into [FacilityList] values(23356,'Kwabome Medical Clinic')
insert into [FacilityList] values(23359,'Makindu Medical Center - Makindu')
insert into [FacilityList] values(23360,'Bliss GVS Health Care (Telepost Clinic)')
insert into [FacilityList] values(23361,'Bliss GVS Health Care (college House)')
insert into [FacilityList] values(23362,'Mariakani Nursing Home and Rehabilitation Centre (South C)')
insert into [FacilityList] values(23364,'Airtech Medical Clinic')
insert into [FacilityList] values(23365,'Gakira Family Health Care')
insert into [FacilityList] values(23366,'Kakuzi Limited Makuyu Dispensary')
insert into [FacilityList] values(23367,'Roseben Medical')
insert into [FacilityList] values(23368,'Kombani Mat Clinic')
insert into [FacilityList] values(23370,'Medwin Medical Centre')
insert into [FacilityList] values(23373,'Mihango Community Dispensary')
insert into [FacilityList] values(23374,'Densmile Dental Clinic')
insert into [FacilityList] values(23375,'Shamsu Health Care')
insert into [FacilityList] values(23376,'TRINITY MEDICAL CLINIC')
insert into [FacilityList] values(23377,'Maple Grove Medical Centre')
insert into [FacilityList] values(23382,'Busia Healthsidelab Medical Clinic')
insert into [FacilityList] values(23393,'Bukaan Deeq Nursing Home')
insert into [FacilityList] values(23396,'Gagaba Dispensary')
insert into [FacilityList] values(23397,'Osani Community Health & Dev Centre')
insert into [FacilityList] values(23399,'Bristol Park Hospital Utawala')
insert into [FacilityList] values(23401,'Modogashe Clinic and Lab Services')
insert into [FacilityList] values(23402,'Qoqar')
insert into [FacilityList] values(23403,'Bliss GVS Health Care Center Othaya')
insert into [FacilityList] values(23404,'Muhotetu Medical Clinic')
insert into [FacilityList] values(23405,'Agakhan University Hospital Valley Arcade Clinic')
insert into [FacilityList] values(23406,'AFARSHANLE DISPENSARY')
insert into [FacilityList] values(23411,'Sinendet Health Options')
insert into [FacilityList] values(23412,'Gold star drop in centre')
insert into [FacilityList] values(23413,'ONGENG COMMUNITY MEDICAL CLINIC')
insert into [FacilityList] values(23414,'Kware Dispensary')
insert into [FacilityList] values(23418,'Chepkoilel Sisiwa Dispensary')
insert into [FacilityList] values(23423,'Equra Health Kenya')
insert into [FacilityList] values(23427,'Nemu Medical Clinic')
insert into [FacilityList] values(23429,'Bunyala Medical Clinic')
insert into [FacilityList] values(23430,'Flomed Medical  Clinic')
insert into [FacilityList] values(23432,'Ringa Health Centre')
insert into [FacilityList] values(23436,'Amani Medical Centre')
insert into [FacilityList] values(23441,'Rapogi Dispensary')
insert into [FacilityList] values(23442,'Ongako Dispensary')
insert into [FacilityList] values(23443,'Aga KhanUniversity Hospital Thika Medical Centre')
insert into [FacilityList] values(23446,'RHAMU NURSING HOME')
insert into [FacilityList] values(23447,'Benane Qokar Dispensary')
insert into [FacilityList] values(23451,'Tiba Bora Medical Centre')
insert into [FacilityList] values(23453,'Asad Medical Centre')
insert into [FacilityList] values(23458,'Kolani Dispensary')
insert into [FacilityList] values(23459,'Libahlow Dispensary')
insert into [FacilityList] values(23462,'Buckner Clinic')
insert into [FacilityList] values(23466,'New Hope Medicare Centre Tinderet')
insert into [FacilityList] values(23470,'St Carol Medical Healthcare Services')
insert into [FacilityList] values(23471,'Emdin Medical Clinic')
insert into [FacilityList] values(23472,'Bububu Community Medical Clinic')
insert into [FacilityList] values(23477,'Almisbah Nursing Home')
insert into [FacilityList] values(23478,'Andiwo Dispensary')
insert into [FacilityList] values(23479,'Kawanga dispensary')
insert into [FacilityList] values(23481,'Bahati Memorial Clinic')
insert into [FacilityList] values(23484,'Lutunda medical centre')
insert into [FacilityList] values(23486,'Chaka Tiba Medical Clinic')
insert into [FacilityList] values(23489,'Garissa ENT Medical Centre')
insert into [FacilityList] values(23492,'King David')
insert into [FacilityList] values(23501,'Shifaa Medical Clinic')
insert into [FacilityList] values(23502,'Bliss GVS Health Care Limited')
insert into [FacilityList] values(23505,'Bliss GVS Healthcare-Embu')
insert into [FacilityList] values(23509,'AKUKURANUT DROP OFF POINT')
insert into [FacilityList] values(23514,'Tionybei Medical Clinic Kabartonjo')
insert into [FacilityList] values(23515,'Tionybei Medical Clinic, Marigat')
insert into [FacilityList] values(23516,'Sagitian Medical Clinic')
insert into [FacilityList] values(23518,'Aljezeera Hospital')
insert into [FacilityList] values(23519,'Imani Medical Clinic & Laboratory Services')
insert into [FacilityList] values(23528,'Vertical care life')
insert into [FacilityList] values(23529,'Pioneer')
insert into [FacilityList] values(23531,'Maumau dispensary')
insert into [FacilityList] values(23532,'Lagdima dispensary')
insert into [FacilityList] values(23533,'Qara Dispensary')
insert into [FacilityList] values(23538,'Bliss GVS Healthcare limited')
insert into [FacilityList] values(23541,'Newa')
insert into [FacilityList] values(23542,'St.Marys Mother & Child Hospital (Kiambu Town )')
insert into [FacilityList] values(23546,'Wa-Theru Medical Clinic')
insert into [FacilityList] values(23558,'Cheplasgei Dispensary')
insert into [FacilityList] values(23561,'Jotram medical center')
insert into [FacilityList] values(23563,'Nagwebonia Highway Medical Clinic')
insert into [FacilityList] values(23567,'Afnaan Health Care Services')
insert into [FacilityList] values(23584,'Bliss GVS Healthcare Ltd. Kitui')
insert into [FacilityList] values(23585,'Boskem Medical clinic')
insert into [FacilityList] values(23596,'Abundant medical')
insert into [FacilityList] values(23597,'Pearl Medical Clinic')
insert into [FacilityList] values(23604,'Stirling Medical Centre')
insert into [FacilityList] values(17894,'Bwiti (Tiomin) Dispensary')
------------------------------------------------------------------------------------------------------