pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["access_rights.htm","Access Rights","Form Builder Access Rights",""],
["access_to_a_dispensing_store.htm","Access to a Dispensing Store","Access to a Dispensing Store",""],
["addacustomfield.htm","Add a Custom Field","Add a Custom Field",""],
["adding_a_laboratory_unit.htm","Adding a Laboratory Unit","Adding a Laboratory Unit",""],
["adding_business_rules.htm","Add Business Rules","Add Business Rules",""],
["adding_dynamic_forms_to_the_hi.htm","Adding Dynamic Forms to the HIV Care Form Set","Adding Dynamic Forms to the HIV Care Form Set",""],
["adding_linked_list_entries_who.htm","Adding Linked List Entries","Adding Linked List Entries",""],
["additional_forms.htm","Additional Forms","Additional Forms",""],
["add_an_entry_in_a_custom_list.htm","Add an Entry in a Custom List","Add an Entry in a Custom List",""],
["add_a_location.htm","Add a Location","Add a Location",""],
["add_a_new_drug.htm","Add a New Drug","Add a New Drug",""],
["add_conditional_fields.htm","Add Conditional Fields","Add Conditional Fields",""],
["add_custom_field_lists.htm","Add Custom Field Lists","Add Custom Field Lists",""],
["add_or_edit_a_user_group.htm","Add or Edit a User Group","Add or Edit a User Group",""],
["add_or_update_a_user.htm","Add or update a User","Add or update a User",""],
["add_sections.htm","Add/Manage Sections","Add/Manage Sections",""],
["adjusting_report_display_size_in_excel_forma.htm","Adjusting Report Display Size","Adjusting Report Display Size In Excel Format",""],
["adjust_stock.htm","Adjust Stock Level","Adjust Stock Level",""],
["adult_and_peds_pharmacy_pmtct.htm","Adult and Peds Pharmacy","Adult and Peds Pharmacy",""],
["adult_pharmacy.htm","Adult Pharmacy 3.1 and below","Adult Pharmacy Form",""],
["adult_pharmacy_2.htm","Adult Pharmacy 3.2 and above","Adult Pharmacy Form",""],
["adult_pharmacy_ar_br.htm","Adult Pharmacy","HIV Care Static Form: Adult Pharmacy",""],
["aidrelief_forms_br.htm","HIV Care Static Forms Data Dictionary","HIV Care Static Forms Data Dictionary",""],
["arformset.htm","HIV Care Form Set","HIV Care Form Set",""],
["arrange_custom_fields_in_forms.htm","Arrange Custom Fields in Forms","Arrange Custom Fields in Forms",""],
["art_care2.htm","ART Care","ART Care",""],
["art_care_br.htm","ART Care","ART Care",""],
["art_follow_up.htm","ART Follow-Up","ART Follow-Up Form",""],
["art_follow_up_ar_br.htm","ART Follow up","ART Follow up",""],
["arv_pick_up_facility.htm","ARV Pick-up","ARV Pick-up Report",""],
["arv_pick_up_report.htm","ARV Pick-up","ARV Pick-up Report",""],
["back_uprestore.htm","Back up/Restore","Back up/Restore",""],
["budget_view.htm","Budget View","Budget View",""],
["business_rule_definitions.htm","Business Rule Definitions","Business Rule Definitions",""],
["carenewform.htm","Create New Form","Create New Form",""],
["care_ended_form.htm","Care Ended Form","Care Ended Form",""],
["care_tracking.htm","Care Ended","Care Ended Form",""],
["care_tracking_ar_br.htm","Care Ended","Care Ended",""],
["care_tracking_pmtct.htm","Care Tracking","Care Tracking",""],
["change_a_custom_field.htm","Change a Custom Field","Change a Custom Field",""],
["change_a_custom_field_lists.htm","Change Custom Field Lists","Change Custom Field Lists",""],
["change_list_entry_priority.htm","Change List Entry Priority","Change List Entry Priority",""],
["change_password.htm","Change Password","Change Password",""],
["clinical_forms.htm","Clinical Forms","Clinical Forms",""],
["common_dynamic_forms_data_dict.htm","Common Dynamic Forms Data Dictionary","Common Dynamic Forms Data Dictionary",""],
["common_static_forms.htm","Common Static Forms Data Dictionary","Common Static Forms Data Dictionary",""],
["configure_additional_labs.htm","Configure Additional Labs","Configure Additional Labs",""],
["configure_backup.htm","Configure Backup","Configure Backup",""],
["configure_budget.htm","Configure Budget","Configure Budget",""],
["configure_care_ended_forms.htm","Configure Care Ended Forms","Configure Care Ended Forms",""],
["configure_custom_fields.htm","Configure Custom Fields","Configure Custom Fields",""],
["configure_iqcare_lists.htm","Configure IQCare Lists","Configure IQCare Lists",""],
["configure_patient_visit.htm","Configure Patient Visit","Configure Patient Visit",""],
["configure_registration_form.htm","Configure Registration Form","Configure Registration Form",""],
["configure_the_scm_module.htm","Configure the PM/SCM Module","Configure the PM/SCM Module",""],
["configuring_lab_units_and_boundary_values.htm","Configuring Lab Units and Boundary Values","Configuring Lab Units and Boundary Values",""],
["configuring_master_lists.htm","Configuring Master Lists","Configuring Master Lists",""],
["cost_allocations.htm","Cost Allocations","Cost Allocations",""],
["create_an_interstore_transfer.htm","Create an Inter-store Transfer","Create an Inter-store Transfer",""],
["create_a_custom_report.htm","Create a Custom Report","Create a Custom Report",""],
["create_a_goods_received_note.htm","Create a Goods Received Note","Create a Goods Received Note",""],
["create_a_purchase_order.htm","Create a Purchase Order","Create a Purchase Order",""],
["create_custom_fields.htm","Create Custom Fields","Create Custom Fields",""],
["create_new_formadditional_forms___ar.htm","Create New Form/Additional Forms","Create New Form/Additional Forms",""],
["create_technical_area.htm","Create Technical Area","Create Technical Area",""],
["customize_lists.htm","Customize Lists","Customize Lists",""],
["customlistbyaidsreliefform.htm","Custom Lists by HIV Care Static Forms","Custom Lists by HIV Care Static Forms",""],
["customreportfieldgroups_ar.htm","Custom Reports Field Groups - AR","Custom Reports Field Groups - AIDSRelief Form Fields",""],
["custom_field_custom_lists.htm","Custom Field Custom Lists","Custom Field Custom Lists",""],
["custom_field_custom_lists2.htm","Navigation","Navigation",""],
["custom_reports.htm","Custom Reports","Custom Reports",""],
["custom_reports_pmtct_fields.htm","Custom Reports with PMTCT Fields","Running Custom Reports with PMTCT Fields",""],
["custom_report_functions.htm","Custom Report Functions","Custom Report Functions",""],
["data_quality_assurance.htm","Data Quality Assurance","Data Quality Assurance",""],
["data_quality_check.htm","Data Quality Check","Data Quality Check",""],
["delete_a_form.htm","Delete a Form","Delete a Form",""],
["delete_patient.htm","Delete patient","Delete patient",""],
["deleting_linked_list_entries_who.htm","Deleting Linked List Entries","Deleting Linked List Entries",""],
["design_and_preview_queries.htm","Design and Preview Queries","Design and Preview Queries",""],
["dispense_drugs.htm","Dispense Drugs","Dispense Drugs",""],
["dispense_drugs2.htm","Dispense Drugs","Dispense Drugs",""],
["display_types_and_business_rul.htm","Display Types and Business Rules","Display Types and Business Rules",""],
["dispose_items.htm","Dispose Items","Dispose Items",""],
["donor_reports.htm","Donor Reports - HIV Care","Donor Reports - HIV Care",""],
["donor_reports_-pmtct.htm","Donor Reports -PMTCT","Donor Reports -PMTCT",""],
["drugs_custom_list.htm","Drugs Custom List","Drugs Custom List",""],
["drug_relationships.htm","Drug Relationships","Drug Relationships",""],
["duplicate_patient_check.htm","Duplicate Patient Check","Duplicate Patient Check",""],
["dynamic_and_manual_entry_queries.htm","Dynamic and Manual Entry Queries","Dynamic and Manual Entry Queries",""],
["edit_an_appointment_via_the_patient_home_pag.htm","Edit An Appointment Via the Patient Home Page","Edit an Appointment Via the Patient Home Page",""],
["edit_an_appointment_via_the_scheduler.htm","Edit An Appointment Via the Scheduler","Edit an Appointment Via the Scheduler",""],
["edit_patient_transfer_information.htm","Edit Patient Transfer Information","Edit Patient Transfer Information",""],
["employee_list.htm","Employee List","Employee List",""],
["enrollment_ar_br.htm","Enrollment","HIV Care Static Form: Enrollment",""],
["enrollment_form.htm","Enrollment","Enrollment Form",""],
["export.htm","Export","Export",""],
["exporting_data.htm","Exporting Data","Exporting Data",""],
["export_a_report.htm","Export a Report","Export a Report",""],
["exposed_infant2.htm","Exposed Infant Follow up","Exposed Infant Follow up",""],
["exposed_infant_br.htm","Exposed Infant","Exposed Infant",""],
["facilityhomepagebusrules.htm","Facility Home Page Business Rules","Facility Home Page Business Rules",""],
["facilitylevelfeatures.htm","Facility Level Features","Facility Level Features",""],
["facilitypatientnavigation.htm","Facility and Patient Navigation","Facility and Patient Navigation",""],
["facilitysatellite_page_field_details.htm","Facility/Satellite Page Field Details","Facility/Satellite Page Field Details",""],
["facility_reports.htm","Facility Reports - HIV Care","Facility Reports - HIV Care",""],
["facility_reports_-_pmtct.htm","Facility Reports - PMTCT","Facility Reports - PMTCT",""],
["facility_setup_and_patient_number.htm","Facility Setup and Patient Number","Facility Setup and the HIV Care Patient Number",""],
["family_information_form.htm","Family Information","Family Information Form",""],
["family_informaton_ar_br.htm","Family Information","HIV Care Static Form: Family Information",""],
["field_level_validation.htm","Field Level Validation","Field Level Validation",""],
["field_search.htm","Field Search and Filter","Field Search and Filter",""],
["filtering_patient_location_and_treatment_loc.htm","Patient and Treatment Location","Filtering on Patient and/or Treatment Location",""],
["findadd_patient.htm","Find/Add Patient","Find/Add Patient",""],
["findadd_patients_and_location.htm","Find/Add Patients and Location","Find/Add Patients and Location",""],
["follow_up_education.htm","Follow up Education","Follow up Education",""],
["follow_up_education2.htm","Follow up Education","Follow up Education",""],
["forms_use_across_different_cou.htm","Forms Used Across Different Countries","Forms Used Across Different Countries",""],
["form_builder_process.htm","Form Builder Process","Form Builder Process",""],
["form_flow_ar.htm","Form Flow","Form Flow",""],
["glossary_and_definition_of_terms.htm","Glossary and Definition of Terms","Glossary and Definition of Terms",""],
["hiv_art_care_card_kenya.htm","HIV/ART Care Card (Kenya)","HIV/ART Care Card (Kenya)",""],
["hiv_care_art_encounter.htm","HIV Care/ART Encounter","HIV Care/ART Encounter",""],
["hiv_care_encounter_br.htm","HIV Care/ART Encounter","HIV Care/ART Encounter",""],
["hiv_care_fields.htm","HIV Care Fields","HIV Care Fields",""],
["hiv_exposed_infant_fu_card.htm","HIV Exposed Infant Follow up Card","HIV Exposed Infant Follow up Card",""],
["home_visit.htm","Home Visit","Home Visit Form",""],
["home_visit_ar_br.htm","Home Visit","Home Visit",""],
["how_lab_unit_configuration_changes_impact_th.htm","How Lab Unit Configuration Changes Impact the Lab Order Form","How Lab Unit Configuration Changes Impact the Lab Order Form",""],
["import_and_run_a_report.htm","Import and Run a Report"," Import and Run a Report",""],
["import_export_forms.htm","Import/Export Forms","Import/Export Forms and Home Pages",""],
["inactivate_a_custom_field.htm","Inactivate a Custom Field","Inactivate a Custom Field",""],
["inactivate_a_drug.htm","Inactivate a Drug","Inactivate a Drug",""],
["inactivate_a_field.htm","Inactivate/Delete a Field","Inactivate/Delete a Field",""],
["inactivate_a_location.htm","Edit/Inactivate a Location","Inactivate a Location",""],
["inactivate_a_user.htm","Inactivate a User","Inactivate a User",""],
["initial_evaluation_ar_br.htm","Initial Evaluation","HIV Care Static Form: Initial Evaluation",""],
["initial_evaluation_form.htm","Initial Evaluation","Initial Evaluation Form",""],
["initial_product_configuration.htm","Initial Product Configuration","Initial Product Configuration",""],
["international_standards.htm","International Standards","International Standards",""],
["iqcare_capabilities.htm","IQCare Capabilities","IQCare Capabilities",""],
["iqcare_configuration.htm","Configuration and Administration","IQCare Configuration and Administration ",""],
["iqcare_management.htm","IQCare Management/Form Builder","IQCare Management/Form Builder",""],
["iqcare_management_login.htm","Login","Login",""],
["iqcare_module.htm","IQCare Clinical Interface, Configuration, Form Builder","IQCare Clinical Interface, Configuration, Form Builder",""],
["iqcare_service.htm","IQCare Service","IQCare Service",""],
["kenyan_moh_blue_card.htm","Kenya MOH 257 Blue Card","Kenya MOH 257 Blue Card",""],
["kenya_moh_clinical_forms.htm","Kenya MOH Clinical Forms","Kenya MOH Clinical Forms",""],
["ke_anc_register_moh_405.htm","ANC Register MOH 405","ANC Register MOH 405",""],
["ke_cervical_cancer.htm","Cervical Cancer Case Finding","Cervical Cancer Case Finding",""],
["ke_hiv_exposed_infant_follow_up_c.htm","HIV Exposed Infant Follow up Card","HIV Exposed Infant Follow up Card",""],
["ke_hiv_testing_counseling_lab_mo.htm","HIV Testing &#38; Counseling Lab MOH 362","HIV Testing &#38; Counseling Lab MOH 362",""],
["ke_maternal__exposed_infant_regis.htm","Maternal &#38; Exposed Infant Registers","Maternal &#38; Exposed Infant Registers",""],
["ke_maternity_register_moh_333.htm","Maternity Register MOH 333","Maternity Register MOH 333",""],
["ke_nutritiion_and_hiv_aids_register.htm","Nutrition and HIV/AIDS Register","Nutrition and HIV/AIDS Register",""],
["ke_pep_register.htm","PEP Register","Post Exposure Prophylaxis Register",""],
["ke_post_natal_register_moh_406.htm","Post Natal Register MOH 406","Post Natal Register MOH 406",""],
["ke_tb_intensive_case_finding.htm","TB Intensive Case Finding","TB Intensive Case Finding",""],
["laboratory_ar_br.htm","Laboratory","HIV Care Static Form: Laboratory",""],
["laboratory_orderlaboratory_results.htm","Laboratory Order/Results","Laboratory Order/Laboratory Results Form",""],
["lab_order_form_configuration.htm","Lab Order Form Configuration","Lab Order Form Configuration",""],
["login_page.htm","Login Page","Login Page",""],
["make_a_back_up.htm","Make a Back up","Make a Back up",""],
["manage_care_ended_fields.htm","Manage Care Ended Fields","Manage Care Ended Fields",""],
["manage_care_ended_forms.htm","Manage Care Ended Forms","Manage Care Ended Forms",""],
["manage_fields.htm","Manage Fields","Manage Fields",""],
["manage_forms.htm","Manage Forms","Manage Forms",""],
["manage_forms_window.htm","Manage Forms Window","Manage Forms Window",""],
["manage_home_pages.htm","Configure Home Pages","Configure Home Pages",""],
["manage_inventory.htm","Manage Inventory","Manage Inventory",""],
["manage_registration_fields.htm","Manage Registration Fields","Manage Registration Fields",""],
["manage_registration_form.htm","Manage Registration Form","Manage Registration Form",""],
["manage_technical_areas.htm","Manage Technical Areas","Manage Technical Areas",""],
["missed_arv_pick_up.htm","Missed ARV Pick-up","Missed ARV Pick-up Report",""],
["ml-_adjustment_reason.htm","ML- Adjustment Reason","ML- Adjustment Reason",""],
["ml-_batch_number.htm","ML- Batch Number","ML- Batch Number",""],
["ml-_cost_allocation_category.htm","ML- Cost Allocation Category","ML- Cost Allocation Category",""],
["ml-_donor_name.htm","ML- Donor Name","ML- Donor Name",""],
["ml-_donor_program_linking.htm","ML- Donor Program Linking","ML- Donor Program Linking",""],
["ml-_drug_type.htm","ML- Drug Type (Item sub-type)","ML- Drug Type (Item sub-type)",""],
["ml-_item_configuration.htm","ML- Item Configuration","ML- Item Configuration",""],
["ml-_item_type.htm","ML- Item Type","ML- Item Type",""],
["ml-_item_type_sub-type_linking.htm","ML- Item Type Sub-Type Linking","ML- Item Type Sub-Type Linking",""],
["ml-_lab_test.htm","ML- Lab Test","ML- Lab Test",""],
["ml-_lab_test_location.htm","ML- Lab Test Location","ML- Lab Test Location",""],
["ml-_manufacturer_detail.htm","ML- Manufacturer Detail","ML- Manufacturer Detail",""],
["ml-_program.htm","ML- Program","ML- Program",""],
["ml-_program_item_linking.htm","ML- Program Item Linking","ML- Program Item Linking",""],
["ml-_purchasing_dispensing_unit.htm","ML- Purchasing/Dispensing Unit","ML- Purchasing/Dispensing Unit",""],
["ml-_return_reason.htm","ML- Return Reason","ML- Return Reason",""],
["ml-_store_detail.htm","ML- Store Detail","ML- Store Detail",""],
["ml-_store_item_linking.htm","ML- Store Item Linking","ML- Store Item Linking",""],
["ml-_store_source_destination_l.htm","ML- Store Source Destination Linking","ML- Store Source Destination Linking",""],
["ml-_store_user_linking.htm","ML- Store User Linking","ML- Store User Linking",""],
["ml-_supplier.htm","ML- Supplier","ML- Supplier",""],
["ml-_supplier_item_linking.htm","ML- Supplier Item Linking","ML- Supplier Item Linking",""],
["new_appointment_via_a_form.htm","New Appointment Via A Form","Make a New Appointment Via A Form",""],
["new_appointment_via_the_patient_home.htm","New Appointment Via The Patient Home Page","Make a New Appointment Via The Patient Home Page",""],
["new_appointment_via_the_scheduler.htm","New Appointment Via The Scheduler","Make a New Appointment Via The Scheduler",""],
["nigeria_monthly_naca_report.htm","Nigeria NACA","Nigeria NACA Monthly Report",""],
["non-art_follow_up_ar_br.htm","Non-ART Follow up","HIV Care Static Form: Non-ART Follow up",""],
["non_art_follow_up.htm","Non-ART Follow-Up","Non-ART Follow-Up Form",""],
["opening_stock.htm","Opening Stock","Opening Stock",""],
["other_user_guides.htm","Installation Guides","Installation Guides",""],
["overview.htm","IQCare - Overview","IQCare - Overview",""],
["paediatric_pharmacy.htm","Paediatric Pharmacy 3.1 and below","Paediatric Pharmacy Form",""],
["paediatric_pharmacy_2.htm","Paediatric Pharmacy 3.2 and above","Paediatric Pharmacy Form",""],
["paperless_facility.htm","Paperless Facility","Paperless Facility",""],
["patienthomepagebusrules.htm","Patient Home Page Business Rules","Patient Home Page Business Rules",""],
["patientlevelfeatures.htm","Patient Level Features","Patient Level Features",""],
["patient_enrolled_by_month.htm","Patient Enrolled by Month","Patient Enrolled by Month Report",""],
["patient_profile_report.htm","Patient Profile","Patient Profile Report",""],
["patient_reports.htm","Patient Reports","Patient Reports",""],
["patient_status_rules.htm","Patient Status Rules","Patient Status Rules",""],
["patient_transfer.htm","Patient Transfer","Patient Transfer",""],
["pediatric_pharmacy_ar_br.htm","Paediatric Pharmacy","HIV Care Static Form: Paediatric Pharmacy",""],
["placeholder_field.htm","Placeholder Field","Placeholder Field",""],
["pmtct_fields.htm","PMTCT Fields","PMTCT Fields",""],
["pmtct_form_naming_convention.htm","PMTCT Form Naming Convention","PMTCT Form Naming Convention",""],
["pmtct_form_set.htm","PMTCT Form Set","PMTCT Form Set",""],
["pre-defined_fields.htm","Pre-defined Fields","Pre-defined Fields",""],
["predefinedcustomlists.htm","Pre-defined Custom Lists","Pre-defined Custom Lists",""],
["predefinedreports.htm","Pre-Defined Reports","Pre-Defined Reports",""],
["prepsteps.htm","Preparation Steps","Preparation Steps",""],
["prior_art_hiv_care2.htm","Prior ART HIV Care","Prior ART HIV Care",""],
["prior_art_hiv_care_br.htm","Prior ART HIV Care","Prior ART HIV Care",""],
["product_configurationfacility_set_up.htm","Product Configuration/Facility Set up","Product Configuration/Facility Set up",""],
["program_management_overview.htm","Program Management Overview","Program Management Overview",""],
["publish_forms.htm","Publish Forms","Publish Forms",""],
["quality_assurance.htm","Quality Assurance","Quality Assurance Report",""],
["query_builder_navigation.htm","Query Builder Navigation","Query Builder Navigation",""],
["query_builder_reports.htm","Query Builder Reports","Query Builder Reports",""],
["reactivating_a_patient.htm","Reactivating a Patient","Reactivating a Patient",""],
["refresh_caches.htm","Refresh Caches","Refresh Caches",""],
["refresh_reporting_tables.htm","Refresh Reporting Tables","Refresh Reporting Tables",""],
["refresh_system_cache.htm","Refresh System Cache","Refresh System Cache",""],
["registration_link.htm","Registration Link","Registration Link",""],
["report_on_custom_fields.htm","Report on Custom Fields","Report on Custom Fields",""],
["report_on_laboratory_results.htm","Report on Laboratory Results","Report on Laboratory Results",""],
["required_fields.htm","Required Fields","Required Fields",""],
["restore_a_database.htm","Restore a database","Restore a database",""],
["restricted_and_unrestricted_lists.htm","Restricted and Unrestricted Lists","Restricted and Unrestricted Lists",""],
["return_drugs.htm","Return Drugs","Return Drugs",""],
["save_and_retrieve_queries.htm","Save and Retrieve Queries","Save and Retrieve Queries",""],
["scheduler.htm","Appointment Scheduler","Appointment Scheduler",""],
["schedulerupdateprocess.htm","Scheduler Update Process","Scheduler Update Process",""],
["scheduler_appointment_views.htm","Scheduler Appointment Views","Scheduler Appointment Views",""],
["scm_and_paperless_mo.htm","SCM and Paperless Modes","SCM and Paperless Modes",""],
["scm_overview.htm","PM/SCM Overview","PM/SCM Overview",""],
["scm_pm_module.htm","IQCare Supply Chain Management","IQCare Supply Chain Management",""],
["select_technical_area.htm","Select Technical Area","Select Technical Area",""],
["setting_the_e-signature.htm","Setting the e-Signature","Setting the e-Signature",""],
["set_form_display_order.htm","Set Form Display Order","Set Form Display Order",""],
["special_forms_linking.htm","Special Forms Linking","Special Forms Linking",""],
["special_privileges_feature.htm","Special Privileges Feature","Special Privileges Feature",""],
["static_forms_data_dicationarie.htm","Forms Data Dicationaries","Forms Data Dicationaries",""],
["tanzania_nacp.htm","Tanzania NACP","Tanzania NACP Monthly/Quarterly Report",""],
["tb_data.htm","TB Data","TB Data",""],
["technical_support.htm","Technical Support","Technical Support",""],
["the_facility_home_page.htm","Facility Home Page","Facility Home Page",""],
["the_patient_home_page.htm","Patient Home Page","Patient Home Page",""],
["the_system_admin_user.htm","The System Admin User","The System Admin User",""],
["track_1_0.htm","Track 1.0","Track 1.0 Report",""],
["track_1_0_exposed_infants.htm","Track 1.0 Exposed Infants","Track 1.0 HIV Exposed Infants",""],
["track_1_0_pmtct.htm","Track 1.0 PMTCT","Track 1.0 PMTCT",""],
["transferringpatientswithnationalpatientnumbers.htm","Transferring Patient with National Patient Numbers","Transferring Patients with National Patient Numbers",""],
["transfer_a_patient.htm","Transfer a Patient","Transfer a Patient",""],
["turning_on_scm_pm.htm","Turning on SCM/PM","Turning on SCM/PM",""],
["uganda_blue_card_data_dictrion.htm","Uganda Blue Card Data Dictrionary","Uganda Blue Card Data Dictrionary",""],
["uganda_blue_card_form_set.htm","HIV/ART Care Form Set (Uganda)","HIV/ART Care Form Set (Uganda)",""],
["universal_registration_form.htm","Universal Registration Form","Universal Registration Form",""],
["universal_registration_form2.htm","Universal Registration Form","Universal Registration Form",""],
["updateunrestrictedlist.htm","Update an Entry in an Unrestricted Custom List","Update an Entry in an Unrestricted Custom List",""],
["update_an_entry_in_a_restricted_custom_list.htm","Update an Entry in a Restricted Custom List","Update an Entry in a Restricted Custom List",""],
["update_business_rules.htm","Update Business Rules","Update Business Rules",""],
["update_conditional_fields.htm","Update/Remove Conditional Fields","Update/Remove Conditional Fields",""],
["update_custom_fields.htm","Update Custom Fields","Update Custom Fields",""],
["user_administration.htm","User Administration","User Administration",""],
["user_group_administration.htm","User Group Administration","User Group Administration",""],
["user_passwords.htm","User Passwords","User Passwords",""],
["using_the_iqcare_picker_tool.htm","Using the IQCare Picker Tool","Using the IQCare Picker Tool",""],
["view_existing_forms.htm","View Existing Forms","View Existing Forms",""],
["view_patient_level_expenditure.htm","View Patient Costs/Debit Note","View Patient Costs/Debit Note",""]];
