CREATE TABLE [dbo].[HeiLabTests](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LabOrderId] [int] NOT NULL,
	[HeiLabTestTypeId] [int] NOT NULL,
 CONSTRAINT [PK_HeiLabTests] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


