//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQCare.Web.CCC.Encounter {
    
    
    public partial class LabOrder {
        
        /// <summary>
        /// ucPatientBrief control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IQCare.Web.CCC.UC.ucPatientBrief ucPatientBrief;
        
        /// <summary>
        /// ucPatientLabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IQCare.Web.CCC.UC.ucPatientLabs ucPatientLabs;
        
        /// <summary>
        /// ucExtruder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IQCare.Web.CCC.UC.ucExtruder ucExtruder;
    }
}
