If Not Exists(Select 1 From LookupMaster where Name='MaternalDrugAdministration') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('MaternalDrugAdministration','MaternalDrugAdministration',0); End

-- LOOKUPITEM
If Not Exists(Select 1 From LookupItem where Name='Vitamin A Supplementation') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Vitamin A Supplementation','Vitamin A Supplementation',0); End
If Not Exists(Select 1 From LookupItem where Name='Started HAART in ANC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Started HAART in ANC','Started HAART in ANC',0); End
If Not Exists(Select 1 From LookupItem where Name='ARVs Started in Maternity') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ARVs Started in Maternity','ARVs Started in Maternity',0); End
If Not Exists(Select 1 From LookupItem where Name='Infant Provided With ARV prophylaxis') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Infant Provided With ARV prophylaxis','Infant Provided With ARV prophylaxis',0); End
If Not Exists(Select 1 From LookupItem where Name='Cotrimoxazole') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Cotrimoxazole','Cotrimoxazole',0); End

--LOOKUPMASTERITEM
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Vitamin A Supplementation')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Vitamin A Supplementation'),'Vitamin A Supplementation',1) end;
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Started HAART in ANC')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Started HAART in ANC'),'Started HAART in ANC',2) end;
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='ARVs Started in Maternity')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='ARVs Started in Maternity'),'ARVs Started in Maternity',3) end;
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Infant Provided With ARV prophylaxis')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Infant Provided With ARV prophylaxis'),'Infant Provided With ARV prophylaxis',4) end;
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Cotrimoxazole')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='MaternalDrugAdministration'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Cotrimoxazole'),'Cotrimoxazole',5) end;