------------Tracing (Phone)
-- master
If Not Exists(Select 1 From LookupMaster where Name='TracingReasonNotContactedPhone') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TracingReasonNotContactedPhone','TracingReasonNotContactedPhone',0); End

-- lookupitem
If Not Exists(Select 1 From LookupItem where Name='No locator information in record') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('No locator information in record','No locator information in record',0); End
If Not Exists(Select 1 From LookupItem where Name='Incorrect locator information in record') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Incorrect locator information in record','Incorrect locator information in record',0); End
If Not Exists(Select 1 From LookupItem where Name='Mteja, calls not going through, not picking calls') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Mteja, calls not going through, not picking calls','Mteja, calls not going through, not picking calls',0); End
If Not Exists(Select 1 From LookupItem where Name='Died') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Died','Died',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End


-- LookupMasterItem
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='No locator information in record')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='No locator information in record'),'No locator information in record',1); end
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Incorrect locator information in record')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Incorrect locator information in record'),'Incorrect locator information in record',2); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Mteja, calls not going through, not picking calls')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Mteja, calls not going through, not picking calls'),'Mteja, calls not going through, not picking calls',3); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Died')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Died'),'Died',4); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Other')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhone'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Other'),'Other',5); end 



------------Tracing (Physical)
-- master
If Not Exists(Select 1 From LookupMaster where Name='TracingReasonNotContactedPhysical') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TracingReasonNotContactedPhysical','TracingReasonNotContactedPhysical',0); End

-- lookupitem
If Not Exists(Select 1 From LookupItem where Name='No locator information in record') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('No locator information in record','No locator information in record',0); End
If Not Exists(Select 1 From LookupItem where Name='Incorrect locator information in record') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Incorrect locator information in record','Incorrect locator information in record',0); End
If Not Exists(Select 1 From LookupItem where Name='Migrated from reported location') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Migrated from reported location','Migrated from reported location',0); End
If Not Exists(Select 1 From LookupItem where Name='Not found at home') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Not found at home','Not found at home',0); End
If Not Exists(Select 1 From LookupItem where Name='Died') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Died','Died',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End


-- LookupMasterItem
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='No locator information in record')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='No locator information in record'),'No locator information in record',1); end
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Incorrect locator information in record')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Incorrect locator information in record'),'Incorrect locator information in record',2); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Migrated from reported location')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Migrated from reported location'),'Migrated from reported location',3); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Not found at home')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Not found at home'),'Not found at home',4); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Died')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Died'),'Died',5); end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Other')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='TracingReasonNotContactedPhysical'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Other'),'Other',6); end 
