

 IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PatientPrEPStatus' AND COLUMN_NAME = 'DateField')
 BEGIN
 BEGIN ALTER TABLE PatientPrEPStatus ADD  	[DateField] [DateTime] NULL END; 
 END
