export enum AppEnum {
    CONSENT_TESTING = 1,
    TESTED,
    CONSENT_PARTNER_LISTING,
    IS_POSITIVE,
    IS_REFERRED,
    TESTED_AS,
    ENROLLED,
    PNS_SCREENED,
    PNS_TRACING,
    FAMILY_SCREENED,
    FAMILY_TRACED,
    PERSONID,
    PNS_SCREENED_POSITIVE
}
