--set HTS entry point
If Not Exists(Select 1 From LookupMaster where Name='HTSEntryPoints') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HTSEntryPoints','HTS Entry Points',0); End
If Not Exists(Select 1 From LookupMaster where Name='Disabilities') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('Disabilities','Disabilities',0); End
If Not Exists(Select 1 From LookupMaster where Name='TestedAs') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TestedAs','TestedAs',0); End
If Not Exists(Select 1 From LookupMaster where Name='Strategy') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('Strategy','Strategy',0); End
If Not Exists(Select 1 From LookupMaster where Name='ReasonsPartner') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('ReasonsPartner','Reasons Partner Listing',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVResults') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVResults','HIV Results',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVTestKits') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVTestKits','HIV Test Kits',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVFinalResults') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVFinalResults','HIV Final Results',0); End
If Not Exists(Select 1 From LookupMaster where Name='TracingOutcome') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TracingOutcome','Tracing Outcome',0); End
If Not Exists(Select 1 From LookupMaster where Name='TracingMode') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TracingMode','Tracing Mode',0); End
If Not Exists(Select 1 From LookupMaster where Name='YesNoNA') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('YesNoNA','Yes/No/NA',0); End
If Not Exists(Select 1 From LookupMaster where Name='IpvOutcome') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('IpvOutcome','IpvOutcome',0); End
If Not Exists(Select 1 From LookupMaster where Name='YesNoDeclined') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('YesNoDeclined','YesNoDeclined',0); End
If Not Exists(Select 1 From LookupMaster where Name='PNSRelationship') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('PNSRelationship','PNSRelationship',0); End
If Not Exists(Select 1 From LookupMaster where Name='HivStatus') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HivStatus','HivStatus',0); End

If Not Exists(Select 1 From LookupMaster where Name='PnsApproach') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('PnsApproach','PnsApproach',0); End
If Not Exists(Select 1 From LookupMaster where Name='PnsScreening') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('PnsScreening','PnsScreening',0); End

If Not Exists(Select 1 From LookupMaster where Name='PnsTracingOutcome') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('PnsTracingOutcome','PnsTracingOutcome',0); End
If Not Exists(Select 1 From LookupMaster where Name='FamilyTracingOutcome') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('FamilyTracingOutcome','FamilyTracingOutcome',0); End

If Not Exists(Select 1 From LookupMaster where Name='ReferralReason') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('ReferralReason','ReferralReason',0); End

If Not Exists(Select 1 From LookupMaster where Name='ScreeningHivStatus') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('ScreeningHivStatus','ScreeningHivStatus',0); End
If Not Exists(Select 1 From LookupMaster where Name='FamilyScreening') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('FamilyScreening','FamilyScreening',0); End
If Not Exists(Select 1 From LookupMaster where Name='PriorityPopulation') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('PriorityPopulation','PriorityPopulation',0); End

If Not Exists(Select 1 From LookupMaster where Name='TracingType') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TracingType','TracingType',0); End


If Not Exists(Select 1 From LookupMaster where Name='HTSKeyPopulation') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HTSKeyPopulation','HTSKeyPopulation',0); End
If Not Exists(Select 1 From LookupMaster where Name='TbScreening') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TbScreening','TbScreening',0); End
If Not Exists(Select 1 From LookupMaster where Name='HTSMaritalStatus') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HTSMaritalStatus','HTSMaritalStatus',0); End

--Set look up items
If Not Exists(Select 1 From LookupItem where Name='Maternity') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Maternity','Maternity',0); End
If Not Exists(Select 1 From LookupItem where Name='PITC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PITC','PITC',0); End
If Not Exists(Select 1 From LookupItem where Name='Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Outreach','Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='ANC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ANC','ANC',0); End
If Not Exists(Select 1 From LookupItem where Name='PeD') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PeD','PeD',0); End
If Not Exists(Select 1 From LookupItem where Name='Mobile Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Mobile Outreach','Mobile Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='PMTCT') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PMTCT','PMTCT',0); End
If Not Exists(Select 1 From LookupItem where Name='VMMC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VMMC','VMMC',0); End
If Not Exists(Select 1 From LookupItem where Name='NP') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('NP','NP',0); End
If Not Exists(Select 1 From LookupItem where Name='VI') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VI','VI',0); End
If Not Exists(Select 1 From LookupItem where Name='HB') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HB','HB',0); End
If Not Exists(Select 1 From LookupItem where Name='HTS') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HTS','HTS',0); End
If Not Exists(Select 1 From LookupItem where Name='D: Deaf/Hearing impaired') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('D: Deaf/hearing impaired','D: Deaf/hearing impaired',0); End
If Not Exists(Select 1 From LookupItem where Name='B: Blind/Visually impaired') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('B: Blind/Visually impaired','B: Blind/Visually impaired',0); End
If Not Exists(Select 1 From LookupItem where Name='M: Mentally Challenged') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('M: Mentally Challenged','M: Mentally Challenged',0); End
If Not Exists(Select 1 From LookupItem where Name='P: Physically Challenged') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('P: Physically Challenged','P: Physically Challenged',0); End
If Not Exists(Select 1 From LookupItem where Name='I: Individual') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('I: Individual','I: Individual',0); End
If Not Exists(Select 1 From LookupItem where Name='C: Couple (includes polygamous)') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('C: Couple (includes polygamous)','C: Couple (includes polygamous)',0); End
If Not Exists(Select 1 From LookupItem where Name='HP: Health Facility Patients') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HP: Health Facility Patients','HP: Health Facility Patients',0); End
If Not Exists(Select 1 From LookupItem where Name='NP: Non-Patients') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('NP: Non-Patients','NP: Non-Patients',0); End
If Not Exists(Select 1 From LookupItem where Name='VI: Integrated VCT sites') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VI: Integrated VCT sites','VI: Integrated VCT sites',0); End
If Not Exists(Select 1 From LookupItem where Name='VS: Stand-alone VCT sites') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VS: Stand-alone VCT sites','VS: Stand-alone VCT sites',0); End
If Not Exists(Select 1 From LookupItem where Name='HB: Home-based') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HB: Home-based','HB: Home-based',0); End
If Not Exists(Select 1 From LookupItem where Name='MO: Mobile and Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('MO: Mobile and Outreach','MO: Mobile and Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='Declined') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Declined','Declined',0); End
If Not Exists(Select 1 From LookupItem where Name='Positive IPV Outcome') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Positive IPV Outcome','Positive IPV Outcome',0); End
If Not Exists(Select 1 From LookupItem where Name='Fear losing partner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Fear losing partner','Fear losing partner',0); End
If Not Exists(Select 1 From LookupItem where Name='Invalid') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Invalid','Invalid',0); End
If Not Exists(Select 1 From LookupItem where Name='Determine') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Determine','Determine',0); End
If Not Exists(Select 1 From LookupItem where Name='First Response') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('First Response','First Response',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End
If Not Exists(Select 1 From LookupItem where Name='Inconclusive') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Inconclusive','Inconclusive',0); End
If Not Exists(Select 1 From LookupItem where Name='Adolescent Girls and Young Women') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Adolescent Girls and Young Women','Adolescent Girls and Young Women',0); End
If Not Exists(Select 1 From LookupItem where Name='Fisher Folk') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Fisher Folk','Fisher Folk',0); End
If Not Exists(Select 1 From LookupItem where Name='MSW') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('MSW','Male Sex Worker',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End
If Not Exists(Select 1 From LookupItem where Name='Prisoner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Prisoner','Prisoner',0); End
If Not Exists(Select 1 From LookupItem where Name='Truck Driver') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Truck Driver','Truck Driver',0); End
If Not Exists(Select 1 From LookupItem where Name='Hts-encounter') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Hts-encounter','hts-encounter',0); End
If Not Exists(Select 1 From LookupItem where Name='Contacted') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Contacted','Contacted',0); End
If Not Exists(Select 1 From LookupItem where Name='Contacted and Linked') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Contacted and Linked','Contacted and Linked',0); End
If Not Exists(Select 1 From LookupItem where Name='Not Contacted') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Not Contacted','Not Contacted',0); End
If Not Exists(Select 1 From LookupItem where Name='Phone') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Phone','Phone',0); End
If Not Exists(Select 1 From LookupItem where Name='Physical') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Physical','Physical',0); End
If Not Exists(Select 1 From LookupItem where Name='Emotional') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Emotional','Emotional',0); End
If Not Exists(Select 1 From LookupItem where Name='Sexual') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Sexual','Sexual',0); End
If Not Exists(Select 1 From LookupItem where Name='No IPV') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('No IPV','No IPV',0); End
If Not Exists(Select 1 From LookupItem where Name='NA-CHILD') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('NA-CHILD','NA-CHILD',0); End
If Not Exists(Select 1 From LookupItem where Name='S') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('S','S',0); End
If Not Exists(Select 1 From LookupItem where Name='P') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('P','P',0); End
If Not Exists(Select 1 From LookupItem where Name='Sexual Partner (SP)') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Sexual Partner (SP)','Sexual Partner (SP)',0); End
If Not Exists(Select 1 From LookupItem where Name='Injectable Drug User (IDU)') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Injectable Drug User (IDU)','Injectable Drug User (IDU)',0); End
If Not Exists(Select 1 From LookupItem where Name='Child - C') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Child - C','Child - C',0); End
If Not Exists(Select 1 From LookupItem where Name='Con: Contract Referral') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Con: Contract Referral','Con: Contract Referral',0); End
If Not Exists(Select 1 From LookupItem where Name='D: Dual Referral') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('D: Dual Referral','D: Dual Referral',0); End
If Not Exists(Select 1 From LookupItem where Name='Cr: Passive Referral') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Cr: Passive Referral','Cr: Passive Referral',0); End
If Not Exists(Select 1 From LookupItem where Name='Pr: Provider Referral') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Pr: Provider Referral','Pr: Provider Referral',0); End

If Not Exists(Select 1 From LookupItem where Name='ConsentToBeTested') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ConsentToBeTested','ConsentToBeTested',0); End
If Not Exists(Select 1 From LookupItem where Name='ConsentToListPartners') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ConsentToListPartners','ConsentToListPartners',0); End
If Not Exists(Select 1 From LookupItem where Name='ConsentToTestingFamily') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ConsentToTestingFamily','ConsentToTestingFamily',0); End
If Not Exists(Select 1 From LookupItem where Name='ConsentToTestingPartner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ConsentToTestingPartner','ConsentToTestingPartner',0); End


If Not Exists(Select 1 From LookupItem where Name='PnsPhysicallyHurt') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PnsPhysicallyHurt','PnsPhysicallyHurt',0); End
If Not Exists(Select 1 From LookupItem where Name='PnsThreatenedHurt') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PnsThreatenedHurt','PnsThreatenedHurt',0); End
If Not Exists(Select 1 From LookupItem where Name='PnsForcedSexual') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PnsForcedSexual','PnsForcedSexual',0); End
If Not Exists(Select 1 From LookupItem where Name='IPVOutcome') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('IPVOutcome','IPVOutcome',0); End
If Not Exists(Select 1 From LookupItem where Name='PnsRelationship') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PnsRelationship','PnsRelationship',0); End
If Not Exists(Select 1 From LookupItem where Name='LivingWithClient') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('LivingWithClient','LivingWithClient',0); End
If Not Exists(Select 1 From LookupItem where Name='HIVStatus') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HIVStatus','HIVStatus',0); End
If Not Exists(Select 1 From LookupItem where Name='PNSApproach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PNSApproach','PNSApproach',0); End
If Not Exists(Select 1 From LookupItem where Name='EligibleTesting') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('EligibleTesting','EligibleTesting',0); End

If Not Exists(Select 1 From LookupItem where Name='CCCEnrollment') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('CCCEnrollment','CCCEnrollment',0); End
If Not Exists(Select 1 From LookupItem where Name='HIVTesting') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HIVTesting','HIVTesting',0); End
If Not Exists(Select 1 From LookupItem where Name='Nutritional') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Nutritional','Nutritional',0); End
If Not Exists(Select 1 From LookupItem where Name='Counselling') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Counselling','Counselling',0); End

If Not Exists(Select 1 From LookupItem where Name='HIV Exposed Infant') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HIV Exposed Infant','HIV Exposed Infant',0); End

If Not Exists(Select 1 From LookupItem where Name='ScreeningHivStatus') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ScreeningHivStatus','ScreeningHivStatus',0); End
If Not Exists(Select 1 From LookupItem where Name='EligibleTesting') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('EligibleTesting','EligibleTesting',0); End
If Not Exists(Select 1 From LookupItem where Name='Not Applicable') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Not Applicable','Not Applicable',0); End


If Not Exists(Select 1 From LookupItem where Name='Family') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Family','Family',0); End
If Not Exists(Select 1 From LookupItem where Name='Partner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Partner','Partner',0); End
If Not Exists(Select 1 From LookupItem where Name='Enrolment') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Enrolment','Enrolment',0); End

If Not Exists(Select 1 From LookupItem where Name='SW') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('SW','SW',0); End
If Not Exists(Select 1 From LookupItem where Name='Not Done') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Not Done','Not Done',0); End
If Not Exists(Select 1 From LookupItem where Name='No Signs') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('No Signs','No Signs',0); End

--Set Lookup items for hts entry points
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Maternity',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Maternity'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'MCH',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MCH'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PITC',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PITC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Outreach',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Outreach'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VCT',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VCT'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ANC',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ANC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IPD-Child',7 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='IPD-Child'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IPD-Adult',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='IPD-Adult'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'CCC',9 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='CCC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'OPD',10 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='OPD'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HBTC',11 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HBTC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PeD',12 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PeD'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Mobile Outreach',13 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Mobile Outreach'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PMTCT',14 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PMTCT'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'TB',15 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='TB'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',16 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

--Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VI',17 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VI'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
--Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HB',18 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HB'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
--Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HTS',19 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HTS'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'D: Deaf/Hearing impaired',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='D: Deaf/Hearing impaired'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'B: Blind/Visually impaired',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='B: Blind/Visually impaired'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'M: Mentally Challenged',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='M: Mentally Challenged'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'P: Physically Challenged',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='P: Physically Challenged'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'I: Individual',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='I: Individual'  ) ItemId FROM LookupMaster  WHERE Name='TestedAs') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'C: Couple (includes polygamous)',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='C: Couple (includes polygamous)'  ) ItemId FROM LookupMaster  WHERE Name='TestedAs') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HP: Health Facility Patients',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HP: Health Facility Patients'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NP: Non-Patients',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='NP: Non-Patients'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VI: Integrated VCT sites',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VI: Integrated VCT sites'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VS: Stand-alone VCT sites',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VS: Stand-alone VCT sites'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HB: Home-based',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HB: Home-based'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'MO: Mobile and Outreach',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MO: Mobile and Outreach'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Declined',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Declined'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive IPV Outcome',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive IPV Outcome'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Fear losing partner',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Fear losing partner'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Invalid',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Invalid'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Determine',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Determine'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'First Response',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='First Response'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Inconclusive',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Inconclusive'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Adolescent Girls and Young Women',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Adolescent Girls and Young Women'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Fisher Folk',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Fisher Folk'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Male Sex Worker',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MSW'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Prisoner',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Prisoner'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Truck Driver',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Truck Driver'  ) ItemId FROM LookupMaster  WHERE Name='PriorityPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


--Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Not Applicable',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Applicable'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Hts-encounter',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Hts-encounter'  ) ItemId FROM LookupMaster  WHERE Name='EncounterType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Contacted',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Contacted') ItemId FROM LookupMaster  WHERE Name='TracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Contacted and Linked',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Contacted and Linked') ItemId FROM LookupMaster  WHERE Name='TracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Not Contacted',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Contacted') ItemId FROM LookupMaster  WHERE Name='TracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Phone',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Phone') ItemId FROM LookupMaster  WHERE Name='TracingMode') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Physical',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Physical') ItemId FROM LookupMaster  WHERE Name='TracingMode') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Yes',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Yes') ItemId FROM LookupMaster  WHERE Name='YesNoNA') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'No',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='No') ItemId FROM LookupMaster  WHERE Name='YesNoNA') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'N/A',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='N/A') ItemId FROM LookupMaster  WHERE Name='YesNoNA') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Physical',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Physical') ItemId FROM LookupMaster  WHERE Name='IpvOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Emotional',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Emotional') ItemId FROM LookupMaster  WHERE Name='IpvOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Sexual',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Sexual') ItemId FROM LookupMaster  WHERE Name='IpvOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'No IPV',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='No IPV') ItemId FROM LookupMaster  WHERE Name='IpvOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NA-CHILD',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='NA-CHILD') ItemId FROM LookupMaster  WHERE Name='IpvOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Yes',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Yes') ItemId FROM LookupMaster  WHERE Name='YesNoDeclined') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'No',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='No') ItemId FROM LookupMaster  WHERE Name='YesNoDeclined') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Declined',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Declined') ItemId FROM LookupMaster  WHERE Name='YesNoDeclined') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'S',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='S') ItemId FROM LookupMaster  WHERE Name='PNSRelationship') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'P',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='P') ItemId FROM LookupMaster  WHERE Name='PNSRelationship') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Sexual Partner (SP)',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Sexual Partner (SP)') ItemId FROM LookupMaster  WHERE Name='PNSRelationship') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Injectable Drug User (IDU)',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Injectable Drug User (IDU)') ItemId FROM LookupMaster  WHERE Name='PNSRelationship') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Child - C',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Child - C') ItemId FROM LookupMaster  WHERE Name='PNSRelationship') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive') ItemId FROM LookupMaster  WHERE Name='HivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative') ItemId FROM LookupMaster  WHERE Name='HivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Unknown',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Unknown') ItemId FROM LookupMaster  WHERE Name='HivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Con: Contract Referral',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Con: Contract Referral') ItemId FROM LookupMaster  WHERE Name='PnsApproach') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'D: Dual Referral',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='D: Dual Referral') ItemId FROM LookupMaster  WHERE Name='PnsApproach') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Cr: Passive Referral',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Cr: Passive Referral') ItemId FROM LookupMaster  WHERE Name='PnsApproach') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Pr: Provider Referral',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Pr: Provider Referral') ItemId FROM LookupMaster  WHERE Name='PnsApproach') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ConsentToBeTested',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ConsentToBeTested') ItemId FROM LookupMaster  WHERE Name='ConsentType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ConsentToListPartners',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ConsentToListPartners') ItemId FROM LookupMaster  WHERE Name='ConsentType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ConsentToTestingFamily',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ConsentToTestingFamily') ItemId FROM LookupMaster  WHERE Name='ConsentType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ConsentToTestingPartner',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ConsentToTestingPartner') ItemId FROM LookupMaster  WHERE Name='ConsentType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PnsPhysicallyHurt',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PnsPhysicallyHurt') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PnsThreatenedHurt',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PnsThreatenedHurt') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PnsForcedSexual',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PnsForcedSexual') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IPVOutcome',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='IPVOutcome') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PnsRelationship',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PnsRelationship') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'LivingWithClient',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='LivingWithClient') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HIVStatus',7 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HIVStatus') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PNSApproach',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PNSApproach') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'EligibleTesting',9 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='EligibleTesting') ItemId FROM LookupMaster  WHERE Name='PnsScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Contacted',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Contacted') ItemId FROM LookupMaster  WHERE Name='PnsTracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Not Contacted',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Contacted') ItemId FROM LookupMaster  WHERE Name='PnsTracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Contacted',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Contacted') ItemId FROM LookupMaster  WHERE Name='FamilyTracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Not Contacted',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Contacted') ItemId FROM LookupMaster  WHERE Name='FamilyTracingOutcome') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'CCCEnrollment',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='CCCEnrollment') ItemId FROM LookupMaster  WHERE Name='ReferralReason') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HIVTesting',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HIVTesting') ItemId FROM LookupMaster  WHERE Name='ReferralReason') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Nutritional',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Nutritional') ItemId FROM LookupMaster  WHERE Name='ReferralReason') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Counselling',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Counselling') ItemId FROM LookupMaster  WHERE Name='ReferralReason') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive') ItemId FROM LookupMaster  WHERE Name='ScreeningHivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative') ItemId FROM LookupMaster  WHERE Name='ScreeningHivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Unknown',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Unknown') ItemId FROM LookupMaster  WHERE Name='ScreeningHivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HIV Exposed Infant',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HIV Exposed Infant') ItemId FROM LookupMaster  WHERE Name='ScreeningHivStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ScreeningHivStatus',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ScreeningHivStatus') ItemId FROM LookupMaster  WHERE Name='FamilyScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'EligibleTesting',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='EligibleTesting') ItemId FROM LookupMaster  WHERE Name='FamilyScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Family',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Family') ItemId FROM LookupMaster  WHERE Name='TracingType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Partner',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Partner') ItemId FROM LookupMaster  WHERE Name='TracingType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Enrolment',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Enrolment') ItemId FROM LookupMaster  WHERE Name='TracingType') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IDU: Intravenous drug users',1 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PWID'  )         ItemId  FROM LookupMaster  WHERE Name='HTSKeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'SW: Sex worker',2 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='SW'  )         ItemId  FROM LookupMaster  WHERE Name='HTSKeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'MSM: Men who have sex with men',3 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MSM'  )         ItemId  FROM LookupMaster  WHERE Name='HTSKeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'O: Others',4 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  )         ItemId  FROM LookupMaster  WHERE Name='HTSKeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NA: Not Applicable',5 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Applicable'  )         ItemId  FROM LookupMaster  WHERE Name='HTSKeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PrTB: Presumed TB',1 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PrTB'  ) ItemId  FROM LookupMaster  WHERE Name='TbScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NS: No Signs',2 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='No Signs'  ) ItemId  FROM LookupMaster  WHERE Name='TbScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ND: Not Done',3 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Done'  ) ItemId  FROM LookupMaster  WHERE Name='TbScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'TBRx: On TB treatment',4 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='TBRx'  ) ItemId  FROM LookupMaster  WHERE Name='TbScreening') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Divorced',1 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Divorced'  )         ItemId  FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Separated',2 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Separated'  )         ItemId  FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Married Polygamous',3 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Married Polygamous'  )         ItemId  FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Single',4 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Single'  )         ItemId  FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Married Monogamous',5 FROM( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Married Monogamous'  )         ItemId  FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Widowed',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Widowed'  ) ItemId FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',7 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Not Applicable',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Not Applicable'  ) ItemId FROM LookupMaster  WHERE Name='HTSMaritalStatus') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;