--set HTS entry point
If Not Exists(Select 1 From LookupMaster where Name='HTSEntryPoints') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HTSEntryPoints','HTS Entry Points',0); End
If Not Exists(Select 1 From LookupMaster where Name='Disabilities') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('Disabilities','Disabilities',0); End
If Not Exists(Select 1 From LookupMaster where Name='TestedAs') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('TestedAs','TestedAs',0); End
If Not Exists(Select 1 From LookupMaster where Name='Strategy') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('Strategy','Strategy',0); End
If Not Exists(Select 1 From LookupMaster where Name='ReasonsPartner') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('ReasonsPartner','Reasons Partner Listing',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVResults') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVResults','HIV Results',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVTestKits') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVTestKits','HIV Test Kits',0); End
If Not Exists(Select 1 From LookupMaster where Name='HIVFinalResults') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('HIVFinalResults','HIV Final Results',0); End

--Set look up items
If Not Exists(Select 1 From LookupItem where Name='Maternity') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Maternity','Maternity',0); End
If Not Exists(Select 1 From LookupItem where Name='PITC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PITC','PITC',0); End
If Not Exists(Select 1 From LookupItem where Name='Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Outreach','Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='ANC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ANC','ANC',0); End
If Not Exists(Select 1 From LookupItem where Name='PeD') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PeD','PeD',0); End
If Not Exists(Select 1 From LookupItem where Name='Mobile Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Mobile Outreach','Mobile Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='PMTCT') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('PMTCT','PMTCT',0); End
If Not Exists(Select 1 From LookupItem where Name='VMMC') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VMMC','VMMC',0); End
If Not Exists(Select 1 From LookupItem where Name='NP') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('NP','NP',0); End
If Not Exists(Select 1 From LookupItem where Name='VI') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VI','VI',0); End
If Not Exists(Select 1 From LookupItem where Name='HB') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HB','HB',0); End
If Not Exists(Select 1 From LookupItem where Name='HTS') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HTS','HTS',0); End
If Not Exists(Select 1 From LookupItem where Name='D: Deaf/Hearing impaired') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('D: Deaf/hearing impaired','D: Deaf/hearing impaired',0); End
If Not Exists(Select 1 From LookupItem where Name='B: Blind/Visually impaired') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('B: Blind/Visually impaired','B: Blind/Visually impaired',0); End
If Not Exists(Select 1 From LookupItem where Name='M: Mentally Challenged') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('M: Mentally Challenged','M: Mentally Challenged',0); End
If Not Exists(Select 1 From LookupItem where Name='P: Physically Challenged') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('P: Physically Challenged','P: Physically Challenged',0); End
If Not Exists(Select 1 From LookupItem where Name='I: Individual') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('I: Individual','I: Individual',0); End
If Not Exists(Select 1 From LookupItem where Name='C: Couple (includes polygamous)') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('C: Couple (includes polygamous)','C: Couple (includes polygamous)',0); End
If Not Exists(Select 1 From LookupItem where Name='HP: Health Facility Patients') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HP: Health Facility Patients','HP: Health Facility Patients',0); End
If Not Exists(Select 1 From LookupItem where Name='NP: Non-Patients') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('NP: Non-Patients','NP: Non-Patients',0); End
If Not Exists(Select 1 From LookupItem where Name='VI: Integrated VCT sites') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VI: Integrated VCT sites','VI: Integrated VCT sites',0); End
If Not Exists(Select 1 From LookupItem where Name='VS: Stand-alone VCT sites') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('VS: Stand-alone VCT sites','VS: Stand-alone VCT sites',0); End
If Not Exists(Select 1 From LookupItem where Name='HB: Home-based') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('HB: Home-based','HB: Home-based',0); End
If Not Exists(Select 1 From LookupItem where Name='MO: Mobile and Outreach') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('MO: Mobile and Outreach','MO: Mobile and Outreach',0); End
If Not Exists(Select 1 From LookupItem where Name='Declined') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Declined','Declined',0); End
If Not Exists(Select 1 From LookupItem where Name='Positive IPV Outcome') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Positive IPV Outcome','Positive IPV Outcome',0); End
If Not Exists(Select 1 From LookupItem where Name='Fear losing partner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Fear losing partner','Fear losing partner',0); End
If Not Exists(Select 1 From LookupItem where Name='Invalid') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Invalid','Invalid',0); End
If Not Exists(Select 1 From LookupItem where Name='Determine') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Determine','Determine',0); End
If Not Exists(Select 1 From LookupItem where Name='First Response') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('First Response','First Response',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End
If Not Exists(Select 1 From LookupItem where Name='Inconclusive') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Inconclusive','Inconclusive',0); End
If Not Exists(Select 1 From LookupItem where Name='Adolescent Girls and Young Women') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Adolescent Girls and Young Women','Adolescent Girls and Young Women',0); End
If Not Exists(Select 1 From LookupItem where Name='Fisher Folk') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Fisher Folk','Fisher Folk',0); End
If Not Exists(Select 1 From LookupItem where Name='MSW') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('MSW','Male Sex Worker',0); End
If Not Exists(Select 1 From LookupItem where Name='Other') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Other','Other',0); End
If Not Exists(Select 1 From LookupItem where Name='Prisoner') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Prisoner','Prisoner',0); End
If Not Exists(Select 1 From LookupItem where Name='Truck Driver') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Truck Driver','Truck Driver',0); End

--Set Lookup items for hts entry points
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Maternity',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Maternity'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'MCH',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MCH'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PITC',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PITC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Outreach',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Outreach'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VCT',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VCT'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'ANC',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='ANC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IPD-Child',7 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='IPD-Child'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'IPD-Adult',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='IPD-Adult'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'CCC',9 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='CCC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'OPD',10 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='OPD'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HBTC',11 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HBTC'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PeD',12 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PeD'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Mobile Outreach',13 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Mobile Outreach'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'PMTCT',14 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='PMTCT'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'TB',15 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='TB'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NP',16 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='NP'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VI',17 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VI'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HB',18 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HB'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HTS',19 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HTS'  ) ItemId FROM LookupMaster  WHERE Name='HTSEntryPoints') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'D: Deaf/Hearing impaired',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='D: Deaf/Hearing impaired'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'B: Blind/Visually impaired',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='B: Blind/Visually impaired'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'M: Mentally Challenged',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='M: Mentally Challenged'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'P: Physically Challenged',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='P: Physically Challenged'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='Disabilities') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'I: Individual',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='I: Individual'  ) ItemId FROM LookupMaster  WHERE Name='TestedAs') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'C: Couple (includes polygamous)',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='C: Couple (includes polygamous)'  ) ItemId FROM LookupMaster  WHERE Name='TestedAs') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HP: Health Facility Patients',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HP: Health Facility Patients'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'NP: Non-Patients',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='NP: Non-Patients'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VI: Integrated VCT sites',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VI: Integrated VCT sites'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'VS: Stand-alone VCT sites',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='VS: Stand-alone VCT sites'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'HB: Home-based',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='HB: Home-based'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'MO: Mobile and Outreach',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MO: Mobile and Outreach'  ) ItemId FROM LookupMaster  WHERE Name='Strategy') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Declined',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Declined'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive IPV Outcome',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive IPV Outcome'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Fear losing partner',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Fear losing partner'  ) ItemId FROM LookupMaster  WHERE Name='ReasonsPartner') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;


Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Invalid',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Invalid'  ) ItemId FROM LookupMaster  WHERE Name='HIVResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Determine',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Determine'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'First Response',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='First Response'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='HIVTestKits') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;

Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Negative',1 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Negative'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Positive',2 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Positive'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Inconclusive',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Inconclusive'  ) ItemId FROM LookupMaster  WHERE Name='HIVFinalResults') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Adolescent Girls and Young Women',3 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Adolescent Girls and Young Women'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Fisher Folk',4 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Fisher Folk'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Male Sex Worker',5 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='MSW'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Other',6 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Other'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Prisoner',7 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Prisoner'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;
Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank) SELECT MasterId, ItemId,'Truck Driver',8 FROM ( SELECT Id MasterId, ( SELECT TOP 1 Id  FROM LookupItem   WHERE Name='Truck Driver'  ) ItemId FROM LookupMaster  WHERE Name='KeyPopulation') X where (select count(*) from LookupMasterItem where lookupMasterId=x.MasterId and LookupItemId=x.ItemId )=0;