If Not Exists(Select 1 From LookupMaster where Name='FamilyPlanningMethod') Begin INSERT INTO LookupMaster (Name, DisplayName, DeleteFlag) VALUES ('FamilyPlanningMethod','FamilyPlanningMethod',0); End

-- lookupitem
If Not Exists(Select 1 From LookupItem where Name='Condoms') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Condoms','Condoms',0); End
If Not Exists(Select 1 From LookupItem where Name='Diaphragm/CervicalCap') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Diaphragm/CervicalCap','Diaphragm / CervicalCap',0); End
If Not Exists(Select 1 From LookupItem where Name='ImergencyContraceptivePillsDispense') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('ImergencyContraceptivePillsDispense','Imergency Contraceptive Pills Dispense',0); End
If Not Exists(Select 1 From LookupItem where Name='FertilityAwarenessMethod/PeriodicTable') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('FertilityAwarenessMethod/PeriodicTable','Fertility Awareness Method / Periodic Table',0); End
If Not Exists(Select 1 From LookupItem where Name='Implant') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Implant','Implant',0); End
If Not Exists(Select 1 From LookupItem where Name='Injectable') Begin INSERT INTO LookupItem (Name, DisplayName, DeleteFlag) VALUES ('Injectable','Injectable',0); End

-- LookupMasterItem
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Condoms')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Condoms'),'Condoms',1);end
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Diaphragm/CervicalCap')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Diaphragm/CervicalCap'),'Diaphragm/CervicalCap',2);end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='ImergencyContraceptivePillsDispense')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='ImergencyContraceptivePillsDispense'),'ImergencyContraceptivePillsDispense',3);end 
IF Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='FertilityAwarenessMethod/PeriodicTable')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='FertilityAwarenessMethod/PeriodicTable'),'FertilityAwarenessMethod/PeriodicTable',4);end
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Implant')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Implant'),'Implant',5);end 
If Not Exists(Select 1 From LookupMasterItem where LookupMasterId=(SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod') and LookupItemId=(SELECT TOP 1 Id FROM LookupItem WHERE Name='Injectable')) Begin Insert Into LookupMasterItem(LookupMasterId ,LookupItemId,DisplayName, OrdRank)VALUES((SELECT TOP 1 Id FROM LookupMaster WHERE Name='FamilyPlanningMethod'),(SELECT TOP 1 Id FROM LookupItem WHERE Name='Injectable'),'Injectable',6);end 